// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package networkservices_test

import (
	"fmt"
	"log"
	"regexp"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-beta/google-beta/acctest"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/envvar"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/services/networkservices"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"

	"google.golang.org/api/googleapi"
)

var (
	_ = fmt.Sprintf
	_ = log.Print
	_ = regexp.MatchString
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = resource.TestMain
	_ = terraform.NewState
	_ = envvar.TestEnvVar
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = googleapi.Error{}
	_ = networkservices.Product
)

func TestAccNetworkServicesTelemetryPolicy_networkServicesTelemetryPolicyBasicExample(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"project":       "PROJECT_NAME",
		"resource_name": "tf-test-my-telemetry-policy" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckNetworkServicesTelemetryPolicyDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccNetworkServicesTelemetryPolicy_networkServicesTelemetryPolicyBasicExample(context),
			},
			{
				ResourceName:            "google_network_services_telemetry_policy.default",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"labels", "location", "name", "terraform_labels"},
			},
			{
				ResourceName:       "google_network_services_telemetry_policy.default",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
		},
	})
}

func testAccNetworkServicesTelemetryPolicy_networkServicesTelemetryPolicyBasicExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_network_services_telemetry_policy" "default" {
  provider = google-beta
  name     = "%{resource_name}"
  location = "us-central1"
  labels   = {
    foo = "bar"
  }

  telemetry_target {
    resources = [
      "//staging-run.sandbox.googleapis.com/projects/%{project}/locations/us-central1/services/my-service"
    ]
  }
}
`, context)
}

func TestAccNetworkServicesTelemetryPolicy_networkServicesTelemetryPolicyFullExample(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"project":       "PROJECT_NAME",
		"resource_name": "tf-test-my-telemetry-policy-full" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckNetworkServicesTelemetryPolicyDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccNetworkServicesTelemetryPolicy_networkServicesTelemetryPolicyFullExample(context),
			},
			{
				ResourceName:            "google_network_services_telemetry_policy.default",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"labels", "location", "name", "terraform_labels"},
			},
			{
				ResourceName:       "google_network_services_telemetry_policy.default",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
		},
	})
}

func testAccNetworkServicesTelemetryPolicy_networkServicesTelemetryPolicyFullExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_network_services_telemetry_policy" "default" {
  provider     = google-beta
  name         = "%{resource_name}"
  location     = "us-central1"
  display_name = "Full Telemetry Policy Sample"
  labels       = {
    foo = "bar"
  }

  telemetry_target {
    resources = [
      "//staging-run.sandbox.googleapis.com/projects/%{project}/locations/us-central1/services/my-service"
    ]
  }

  tracing_configuration {
    sampling_rate = 0.5

    custom_span_attributes {
      attribute_name = "env"
      literal_value  = "prod"
    }

    custom_span_attributes {
      attribute_name    = "user-id"
      from_header_value = "x-user-id"
    }

    parent_based_sampling {
      enabled       = true
      sampling_rate = 0.8
    }
  }

  metrics_configuration {
    enabled = true
  }
}
`, context)
}

func TestAccNetworkServicesTelemetryPolicy_networkServicesTelemetryPolicyGlobalExample(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"project":       "PROJECT_NAME",
		"resource_name": "tf-test-my-telemetry-policy-global" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckNetworkServicesTelemetryPolicyDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccNetworkServicesTelemetryPolicy_networkServicesTelemetryPolicyGlobalExample(context),
			},
			{
				ResourceName:            "google_network_services_telemetry_policy.default",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"labels", "location", "name", "terraform_labels"},
			},
			{
				ResourceName:       "google_network_services_telemetry_policy.default",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
		},
	})
}

func testAccNetworkServicesTelemetryPolicy_networkServicesTelemetryPolicyGlobalExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_network_services_telemetry_policy" "default" {
  provider = google-beta
  name     = "%{resource_name}"
  location = "global"
  labels   = {
    foo = "bar"
  }

  telemetry_target {
    resources = [
      "//staging-run.sandbox.googleapis.com/projects/%{project}/locations/us-central1/services/my-service"
    ]
  }
}
`, context)
}

func testAccCheckNetworkServicesTelemetryPolicyDestroyProducer(t *testing.T) func(s *terraform.State) error {
	return func(s *terraform.State) error {
		for name, rs := range s.RootModule().Resources {
			if rs.Type != "google_network_services_telemetry_policy" {
				continue
			}
			if strings.HasPrefix(name, "data.") {
				continue
			}

			config := acctest.GoogleProviderConfig(t)
			url, err := tpgresource.ReplaceVarsForTest(config, rs, transport_tpg.BaseUrl(networkservices.Product, config)+"projects/{{project}}/locations/{{location}}/telemetryPolicies/{{name}}")
			if err != nil {
				return err
			}

			billingProject := ""

			if config.BillingProject != "" {
				billingProject = config.BillingProject
			}

			_, err = transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
				Config:    config,
				Method:    "GET",
				Project:   billingProject,
				RawURL:    url,
				UserAgent: config.UserAgent,
			})
			if err == nil {
				return fmt.Errorf("NetworkServicesTelemetryPolicy still exists at %s", url)
			}
		}

		return nil
	}
}
