// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package compute_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/hashicorp/terraform-provider-google-beta/google-beta/acctest"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/envvar"
)

func TestAccComputeInstanceTemplateIamBindingGenerated(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix": acctest.RandString(t, 10),
		"role":          "roles/viewer",
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccComputeInstanceTemplateIamBinding_basicGenerated(context),
			},
			{
				ResourceName:      "google_compute_instance_template_iam_binding.foo",
				ImportStateId:     fmt.Sprintf("projects/%s/global/instanceTemplates/%s roles/viewer", envvar.GetTestProjectFromEnv(), fmt.Sprintf("tf-test-my-instance-template%s", context["random_suffix"])),
				ImportState:       true,
				ImportStateVerify: true,
			},
			{
				// Test Iam Binding update
				Config: testAccComputeInstanceTemplateIamBinding_updateGenerated(context),
			},
			{
				ResourceName:      "google_compute_instance_template_iam_binding.foo",
				ImportStateId:     fmt.Sprintf("projects/%s/global/instanceTemplates/%s roles/viewer", envvar.GetTestProjectFromEnv(), fmt.Sprintf("tf-test-my-instance-template%s", context["random_suffix"])),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccComputeInstanceTemplateIamMemberGenerated(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix": acctest.RandString(t, 10),
		"role":          "roles/viewer",
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				// Test Iam Member creation (no update for member, no need to test)
				Config: testAccComputeInstanceTemplateIamMember_basicGenerated(context),
			},
			{
				ResourceName:      "google_compute_instance_template_iam_member.foo",
				ImportStateId:     fmt.Sprintf("projects/%s/global/instanceTemplates/%s roles/viewer user:admin@hashicorptest.com", envvar.GetTestProjectFromEnv(), fmt.Sprintf("tf-test-my-instance-template%s", context["random_suffix"])),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccComputeInstanceTemplateIamPolicyGenerated(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix": acctest.RandString(t, 10),
		"role":          "roles/viewer",
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccComputeInstanceTemplateIamPolicy_basicGenerated(context),
				Check:  resource.TestCheckResourceAttrSet("data.google_compute_instance_template_iam_policy.foo", "policy_data"),
			},
			{
				ResourceName:      "google_compute_instance_template_iam_policy.foo",
				ImportStateId:     fmt.Sprintf("projects/%s/global/instanceTemplates/%s", envvar.GetTestProjectFromEnv(), fmt.Sprintf("tf-test-my-instance-template%s", context["random_suffix"])),
				ImportState:       true,
				ImportStateVerify: true,
			},
			{
				Config: testAccComputeInstanceTemplateIamPolicy_emptyBinding(context),
			},
			{
				ResourceName:      "google_compute_instance_template_iam_policy.foo",
				ImportStateId:     fmt.Sprintf("projects/%s/global/instanceTemplates/%s", envvar.GetTestProjectFromEnv(), fmt.Sprintf("tf-test-my-instance-template%s", context["random_suffix"])),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccComputeInstanceTemplateIamMember_basicGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_compute_instance_template" "default" {
  name         = "tf-test-my-instance-template%{random_suffix}"
  machine_type = "e2-medium"

  disk {
    source_image = "debian-cloud/debian-11"
  }

  network_interface {
    network = "default"
  }
}

resource "google_compute_instance_template_iam_member" "foo" {
  project = google_compute_instance_template.default.project
  name = google_compute_instance_template.default.name
  role = "%{role}"
  member = "user:admin@hashicorptest.com"
}
`, context)
}

func testAccComputeInstanceTemplateIamPolicy_basicGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_compute_instance_template" "default" {
  name         = "tf-test-my-instance-template%{random_suffix}"
  machine_type = "e2-medium"

  disk {
    source_image = "debian-cloud/debian-11"
  }

  network_interface {
    network = "default"
  }
}

data "google_iam_policy" "foo" {
  binding {
    role = "%{role}"
    members = ["user:admin@hashicorptest.com"]
  }
}

resource "google_compute_instance_template_iam_policy" "foo" {
  project = google_compute_instance_template.default.project
  name = google_compute_instance_template.default.name
  policy_data = data.google_iam_policy.foo.policy_data
}

data "google_compute_instance_template_iam_policy" "foo" {
  project = google_compute_instance_template.default.project
  name = google_compute_instance_template.default.name
  depends_on = [
    google_compute_instance_template_iam_policy.foo
  ]
}
`, context)
}

func testAccComputeInstanceTemplateIamPolicy_emptyBinding(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_compute_instance_template" "default" {
  name         = "tf-test-my-instance-template%{random_suffix}"
  machine_type = "e2-medium"

  disk {
    source_image = "debian-cloud/debian-11"
  }

  network_interface {
    network = "default"
  }
}

data "google_iam_policy" "foo" {
}

resource "google_compute_instance_template_iam_policy" "foo" {
  project = google_compute_instance_template.default.project
  name = google_compute_instance_template.default.name
  policy_data = data.google_iam_policy.foo.policy_data
}
`, context)
}

func testAccComputeInstanceTemplateIamBinding_basicGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_compute_instance_template" "default" {
  name         = "tf-test-my-instance-template%{random_suffix}"
  machine_type = "e2-medium"

  disk {
    source_image = "debian-cloud/debian-11"
  }

  network_interface {
    network = "default"
  }
}

resource "google_compute_instance_template_iam_binding" "foo" {
  project = google_compute_instance_template.default.project
  name = google_compute_instance_template.default.name
  role = "%{role}"
  members = ["user:admin@hashicorptest.com"]
}
`, context)
}

func testAccComputeInstanceTemplateIamBinding_updateGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_compute_instance_template" "default" {
  name         = "tf-test-my-instance-template%{random_suffix}"
  machine_type = "e2-medium"

  disk {
    source_image = "debian-cloud/debian-11"
  }

  network_interface {
    network = "default"
  }
}

resource "google_compute_instance_template_iam_binding" "foo" {
  project = google_compute_instance_template.default.project
  name = google_compute_instance_template.default.name
  role = "%{role}"
  members = ["user:admin@hashicorptest.com", "user:gterraformtest1@gmail.com"]
}
`, context)
}
