// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/designcenter/Space.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/resource.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package designcenter

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"reflect"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/hashicorp/errwrap"
	"github.com/hashicorp/go-cty/cty"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/id"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/logging"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/structure"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/registry"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/verify"

	"google.golang.org/api/googleapi"
)

var (
	_ = bytes.Clone
	_ = context.WithCancel
	_ = base64.NewDecoder
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = log.Print
	_ = http.Get
	_ = reflect.ValueOf
	_ = regexp.Match
	_ = slices.Min([]int{1})
	_ = sort.IntSlice{}
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = errwrap.Wrap
	_ = cty.BoolVal
	_ = diag.Diagnostic{}
	_ = customdiff.All
	_ = id.UniqueId
	_ = logging.LogLevel
	_ = retry.Retry
	_ = schema.Noop
	_ = validation.All
	_ = structure.ExpandJsonFromString
	_ = terraform.State{}
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = verify.ValidateEnum
	_ = googleapi.Error{}
)

func init() {
	registry.Schema{
		Name:        "google_design_center_space",
		ProductName: "designcenter",
		Type:        registry.SchemaTypeResource,
		Schema:      ResourceDesignCenterSpace(),
	}.Register()
}

func ResourceDesignCenterSpace() *schema.Resource {
	return &schema.Resource{
		Create: resourceDesignCenterSpaceCreate,
		Read:   resourceDesignCenterSpaceRead,
		Update: resourceDesignCenterSpaceUpdate,
		Delete: resourceDesignCenterSpaceDelete,

		Importer: &schema.ResourceImporter{
			State: resourceDesignCenterSpaceImport,
		},

		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(20 * time.Minute),
			Update: schema.DefaultTimeout(20 * time.Minute),
			Delete: schema.DefaultTimeout(20 * time.Minute),
		},

		CustomizeDiff: customdiff.All(
			tpgresource.DefaultProviderProject,
			tpgresource.DefaultProviderDeletionPolicy("DELETE"),
		),

		Identity: &schema.ResourceIdentity{
			Version: 1,
			SchemaFunc: func() map[string]*schema.Schema {
				return map[string]*schema.Schema{
					"location": {
						Type:              schema.TypeString,
						RequiredForImport: true,
					},
					"space_id": {
						Type:              schema.TypeString,
						RequiredForImport: true,
					},
					"project": {
						Type:              schema.TypeString,
						OptionalForImport: true,
					},
				}
			},
		},
		ResourceBehavior: schema.ResourceBehavior{
			MutableIdentity: true,
		},

		Schema: map[string]*schema.Schema{
			"location": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: `Resource ID segment making up resource 'name'. It identifies the resource within its parent collection as described in https://google.aip.dev/122.`,
			},
			"space_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: `The ID of the space to create.`,
			},
			"description": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: `Description for the space.`,
			},
			"display_name": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: `Display name for the space.`,
			},
			"enable_gcp_shared_templates": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: `Flag to enable Google opinionated shared templates.`,
			},
			"gcs_bucket": {
				Type:     schema.TypeString,
				Optional: true,
				Description: `An existing Google Cloud Storage bucket that you want to use instead of
creating a new bucket during Application Design Center setup.
If not provided, a default bucket is created during setup.
The bucket must exist in the same project as the space.
If the bucket name does not exist in the same project as the space, the
request fails with an INVALID_ARGUMENT error.
If you do not have access to the bucket, the request fails with a
PERMISSION_DENIED error.
Format: {$bucket_name}
For example, if the Cloud Storage bucket URI is gs:\/\/{$bucket_name}, the
format is {$bucket_name}.`,
			},
			"tags": {
				Type:     schema.TypeMap,
				Optional: true,
				ForceNew: true,
				Description: `Input only. Immutable. Tags are key/values bound to space resource.
Example:
'''
"123/environment": "production"
"123/costCenter": "marketing"
'''

For more information on tag creation and management, see
https://cloud.google.com/resource-manager/docs/tags/tags-overview.`,
				Elem: &schema.Schema{Type: schema.TypeString},
			},
			"create_time": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `Space creation timestamp.`,
			},
			"name": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `Identifier. The space name.`,
			},
			"update_time": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `Space update timestamp`,
			},
			"project": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
				ForceNew: true,
			},
			"deletion_policy": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
				Description: `Whether Terraform will be prevented from destroying the instance. Defaults to "DELETE".
When a 'terraform destroy' or 'terraform apply' would delete the instance,
the command will fail if this field is set to "PREVENT" in Terraform state.
When set to "ABANDON", the command will remove the resource from Terraform
management without updating or deleting the resource in the API.
When set to "DELETE", deleting the resource is allowed.
`,
			},
		},
		UseJSONNumber: true,
	}
}

func resourceDesignCenterSpaceCreate(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	obj := make(map[string]interface{})
	descriptionProp, err := expandDesignCenterSpaceDescription(d.Get("description"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("description"); !tpgresource.IsEmptyValue(reflect.ValueOf(descriptionProp)) && (ok || !reflect.DeepEqual(v, descriptionProp)) {
		obj["description"] = descriptionProp
	}
	displayNameProp, err := expandDesignCenterSpaceDisplayName(d.Get("display_name"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("display_name"); !tpgresource.IsEmptyValue(reflect.ValueOf(displayNameProp)) && (ok || !reflect.DeepEqual(v, displayNameProp)) {
		obj["displayName"] = displayNameProp
	}
	enableGcpSharedTemplatesProp, err := expandDesignCenterSpaceEnableGcpSharedTemplates(d.Get("enable_gcp_shared_templates"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("enable_gcp_shared_templates"); !tpgresource.IsEmptyValue(reflect.ValueOf(enableGcpSharedTemplatesProp)) && (ok || !reflect.DeepEqual(v, enableGcpSharedTemplatesProp)) {
		obj["enableGcpSharedTemplates"] = enableGcpSharedTemplatesProp
	}
	gcsBucketProp, err := expandDesignCenterSpaceGcsBucket(d.Get("gcs_bucket"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("gcs_bucket"); !tpgresource.IsEmptyValue(reflect.ValueOf(gcsBucketProp)) && (ok || !reflect.DeepEqual(v, gcsBucketProp)) {
		obj["gcsBucket"] = gcsBucketProp
	}
	tagsProp, err := expandDesignCenterSpaceTags(d.Get("tags"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("tags"); !tpgresource.IsEmptyValue(reflect.ValueOf(tagsProp)) && (ok || !reflect.DeepEqual(v, tagsProp)) {
		obj["tags"] = tagsProp
	}

	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/spaces?spaceId={{space_id}}")
	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Creating new Space: %#v", obj)
	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for Space: %s", err)
	}
	billingProject = project

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "POST",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
		Timeout:   d.Timeout(schema.TimeoutCreate),
		Headers:   headers,
	})
	if err != nil {
		return fmt.Errorf("Error creating Space: %s", err)
	}

	// Store the ID now
	id, err := tpgresource.ReplaceVars(d, config, "projects/{{project}}/locations/{{location}}/spaces/{{space_id}}")
	if err != nil {
		return fmt.Errorf("Error constructing id: %s", err)
	}
	d.SetId(id)

	log.Printf("[DEBUG] Finished creating Space %q: %#v", d.Id(), res)

	identity, err := d.Identity()
	if err == nil && identity != nil {
		if locationValue, ok := d.GetOk("location"); ok && locationValue.(string) != "" {
			if err = identity.Set("location", locationValue.(string)); err != nil {
				return fmt.Errorf("Error setting location: %s", err)
			}
		}
		if spaceIdValue, ok := d.GetOk("space_id"); ok && spaceIdValue.(string) != "" {
			if err = identity.Set("space_id", spaceIdValue.(string)); err != nil {
				return fmt.Errorf("Error setting space_id: %s", err)
			}
		}
		if projectValue, ok := d.GetOk("project"); ok && projectValue.(string) != "" {
			if err = identity.Set("project", projectValue.(string)); err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Create) identity not set: %s", err)
	}

	return resourceDesignCenterSpaceRead(d, meta)
}

func resourceDesignCenterSpaceRead(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/spaces/{{space_id}}")
	if err != nil {
		return err
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for Space: %s", err)
	}
	billingProject = project

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "GET",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Headers:   headers,
	})
	if err != nil {
		return transport_tpg.HandleNotFoundError(err, d, fmt.Sprintf("DesignCenterSpace %q", d.Id()))
	}

	log.Printf("[DEBUG] Finished reading DesignCenterSpace %q: %#v", d.Id(), res)

	// Explicitly set virtual fields to default values if unset
	if _, ok := d.GetOkExists("deletion_policy"); !ok {
		//prioritize config's value if present
		if config.DeletionPolicy != "" {
			if err := d.Set("deletion_policy", config.DeletionPolicy); err != nil {
				return fmt.Errorf("Error setting deletion_policy: %s", err)
			}
		} else {
			if err := d.Set("deletion_policy", "DELETE"); err != nil {
				return fmt.Errorf("Error setting deletion_policy: %s", err)
			}
		}
	}
	if err := d.Set("project", project); err != nil {
		return fmt.Errorf("Error reading Space: %s", err)
	}

	err = ResourceDesignCenterSpaceFlatten(d, meta, res, config, project, userAgent, billingProject, url, headers)
	if err != nil {
		return err
	}

	identity, err := d.Identity()
	if err == nil && identity != nil {
		if v, ok := identity.GetOk("location"); !ok && v == "" {
			err = identity.Set("location", d.Get("location").(string))
			if err != nil {
				return fmt.Errorf("Error setting location: %s", err)
			}
		}
		if v, ok := identity.GetOk("space_id"); !ok && v == "" {
			err = identity.Set("space_id", d.Get("space_id").(string))
			if err != nil {
				return fmt.Errorf("Error setting space_id: %s", err)
			}
		}
		if v, ok := identity.GetOk("project"); !ok && v == "" {
			err = identity.Set("project", d.Get("project").(string))
			if err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Read) identity not set: %s", err)
	}

	return nil
}

func resourceDesignCenterSpaceUpdate(d *schema.ResourceData, meta interface{}) error {
	clientSideFields := map[string]bool{"deletion_policy": true}
	clientSideOnly := true
	for field := range ResourceDesignCenterSpace().Schema {
		if d.HasChange(field) && !clientSideFields[field] {
			clientSideOnly = false
			break
		}
	}
	if clientSideOnly {
		log.Print("[DEBUG] Only client-side changes detected. Cancelling update operation.")
		return resourceDesignCenterSpaceRead(d, meta)
	}

	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}
	identity, err := d.Identity()
	if err == nil && identity != nil {
		if locationValue, ok := d.GetOk("location"); ok && locationValue.(string) != "" {
			if err = identity.Set("location", locationValue.(string)); err != nil {
				return fmt.Errorf("Error setting location: %s", err)
			}
		}
		if spaceIdValue, ok := d.GetOk("space_id"); ok && spaceIdValue.(string) != "" {
			if err = identity.Set("space_id", spaceIdValue.(string)); err != nil {
				return fmt.Errorf("Error setting space_id: %s", err)
			}
		}
		if projectValue, ok := d.GetOk("project"); ok && projectValue.(string) != "" {
			if err = identity.Set("project", projectValue.(string)); err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Update) identity not set: %s", err)
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for Space: %s", err)
	}
	billingProject = project

	obj := make(map[string]interface{})
	descriptionProp, err := expandDesignCenterSpaceDescription(d.Get("description"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("description"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, descriptionProp)) {
		obj["description"] = descriptionProp
	}
	displayNameProp, err := expandDesignCenterSpaceDisplayName(d.Get("display_name"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("display_name"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, displayNameProp)) {
		obj["displayName"] = displayNameProp
	}
	enableGcpSharedTemplatesProp, err := expandDesignCenterSpaceEnableGcpSharedTemplates(d.Get("enable_gcp_shared_templates"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("enable_gcp_shared_templates"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, enableGcpSharedTemplatesProp)) {
		obj["enableGcpSharedTemplates"] = enableGcpSharedTemplatesProp
	}
	gcsBucketProp, err := expandDesignCenterSpaceGcsBucket(d.Get("gcs_bucket"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("gcs_bucket"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, gcsBucketProp)) {
		obj["gcsBucket"] = gcsBucketProp
	}

	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/spaces/{{space_id}}")
	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Updating Space %q: %#v", d.Id(), obj)
	headers := make(http.Header)
	updateMask := []string{}

	if d.HasChange("description") {
		updateMask = append(updateMask, "description")
	}

	if d.HasChange("display_name") {
		updateMask = append(updateMask, "displayName")
	}

	if d.HasChange("enable_gcp_shared_templates") {
		updateMask = append(updateMask, "enableGcpSharedTemplates")
	}

	if d.HasChange("gcs_bucket") {
		updateMask = append(updateMask, "gcsBucket")
	}
	// updateMask is a URL parameter but not present in the schema, so ReplaceVars
	// won't set it
	url, err = transport_tpg.AddQueryParams(url, map[string]string{"updateMask": strings.Join(updateMask, ",")})
	if err != nil {
		return err
	}

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	// if updateMask is empty we are not updating anything so skip the post
	if len(updateMask) > 0 {
		res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
			Config:    config,
			Method:    "PATCH",
			Project:   billingProject,
			RawURL:    url,
			UserAgent: userAgent,
			Body:      obj,
			Timeout:   d.Timeout(schema.TimeoutUpdate),
			Headers:   headers,
		})

		if err != nil {
			return fmt.Errorf("Error updating Space %q: %s", d.Id(), err)
		} else {
			log.Printf("[DEBUG] Finished updating Space %q: %#v", d.Id(), res)
		}

	}

	return resourceDesignCenterSpaceRead(d, meta)
}

func resourceDesignCenterSpaceDelete(d *schema.ResourceData, meta interface{}) error {
	if d.Get("deletion_policy").(string) == "PREVENT" {
		return fmt.Errorf("cannot destroy DesignCenterSpace without setting deletion_policy=\"DELETE\" and running `terraform apply`")
	}
	if d.Get("deletion_policy").(string) == "ABANDON" {
		log.Printf("[DEBUG] deletion_policy set to \"ABANDON\", removing Space %q from Terraform state without deletion", d.Id())
		return nil
	}
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for Space: %s", err)
	}
	billingProject = project
	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/spaces/{{space_id}}")
	if err != nil {
		return err
	}

	var obj map[string]interface{}

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)

	log.Printf("[DEBUG] Deleting Space %q", d.Id())
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "DELETE",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
		Timeout:   d.Timeout(schema.TimeoutDelete),
		Headers:   headers,
	})
	if err != nil {
		return transport_tpg.HandleNotFoundError(err, d, "Space")
	}

	log.Printf("[DEBUG] Finished deleting Space %q: %#v", d.Id(), res)
	return nil
}

func resourceDesignCenterSpaceImport(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	config := meta.(*transport_tpg.Config)
	if err := tpgresource.ParseImportId([]string{
		"^projects/(?P<project>[^/]+)/locations/(?P<location>[^/]+)/spaces/(?P<space_id>[^/]+)$",
		"^(?P<project>[^/]+)/(?P<location>[^/]+)/(?P<space_id>[^/]+)$",
		"^(?P<location>[^/]+)/(?P<space_id>[^/]+)$",
	}, d, config); err != nil {
		return nil, err
	}

	// Replace import id for the resource id
	id, err := tpgresource.ReplaceVars(d, config, "projects/{{project}}/locations/{{location}}/spaces/{{space_id}}")
	if err != nil {
		return nil, fmt.Errorf("Error constructing id: %s", err)
	}
	d.SetId(id)

	return []*schema.ResourceData{d}, nil
}

func flattenDesignCenterSpaceCreateTime(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenDesignCenterSpaceDescription(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenDesignCenterSpaceDisplayName(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenDesignCenterSpaceEnableGcpSharedTemplates(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenDesignCenterSpaceGcsBucket(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenDesignCenterSpaceName(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenDesignCenterSpaceTags(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenDesignCenterSpaceUpdateTime(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func expandDesignCenterSpaceDescription(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandDesignCenterSpaceDisplayName(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandDesignCenterSpaceEnableGcpSharedTemplates(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandDesignCenterSpaceGcsBucket(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandDesignCenterSpaceTags(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (map[string]string, error) {
	if v == nil {
		return map[string]string{}, nil
	}
	m := make(map[string]string)
	for k, val := range v.(map[string]interface{}) {
		m[k] = val.(string)
	}
	return m, nil
}

func ResourceDesignCenterSpaceFlatten(d *schema.ResourceData, meta interface{}, res map[string]interface{}, config *transport_tpg.Config, project string, userAgent string, billingProject string, url string, headers http.Header) error {
	var err error

	if err = d.Set("create_time", flattenDesignCenterSpaceCreateTime(res["createTime"], d, config)); err != nil {
		return fmt.Errorf("Error reading Space: %s", err)
	}
	if err = d.Set("description", flattenDesignCenterSpaceDescription(res["description"], d, config)); err != nil {
		return fmt.Errorf("Error reading Space: %s", err)
	}
	if err = d.Set("display_name", flattenDesignCenterSpaceDisplayName(res["displayName"], d, config)); err != nil {
		return fmt.Errorf("Error reading Space: %s", err)
	}
	if err = d.Set("enable_gcp_shared_templates", flattenDesignCenterSpaceEnableGcpSharedTemplates(res["enableGcpSharedTemplates"], d, config)); err != nil {
		return fmt.Errorf("Error reading Space: %s", err)
	}
	if err = d.Set("gcs_bucket", flattenDesignCenterSpaceGcsBucket(res["gcsBucket"], d, config)); err != nil {
		return fmt.Errorf("Error reading Space: %s", err)
	}
	if err = d.Set("name", flattenDesignCenterSpaceName(res["name"], d, config)); err != nil {
		return fmt.Errorf("Error reading Space: %s", err)
	}
	if err = d.Set("tags", flattenDesignCenterSpaceTags(res["tags"], d, config)); err != nil {
		return fmt.Errorf("Error reading Space: %s", err)
	}
	if err = d.Set("update_time", flattenDesignCenterSpaceUpdateTime(res["updateTime"], d, config)); err != nil {
		return fmt.Errorf("Error reading Space: %s", err)
	}

	return nil
}
