// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package observability_test

import (
	"fmt"
	"log"
	"regexp"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-beta/google-beta/acctest"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/envvar"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/services/observability"
	_ "github.com/hashicorp/terraform-provider-google-beta/google-beta/services/resourcemanager"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"

	"google.golang.org/api/googleapi"
)

var (
	_ = fmt.Sprintf
	_ = log.Print
	_ = regexp.MatchString
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = resource.TestMain
	_ = terraform.NewState
	_ = envvar.TestEnvVar
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = googleapi.Error{}
	_ = observability.Product
)

func TestAccObservabilityLink_observabilityLinkBasicExample(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"billing_account": envvar.GetTestBillingAccountFromEnv(t),
		"org_id":          envvar.GetTestOrgFromEnv(t),
		"description":     "Initial description",
		"display_name":    "Initial Display Name",
		"random_suffix":   randomSuffix,
	}

	context_1 := map[string]interface{}{
		"billing_account": envvar.GetTestBillingAccountFromEnv(t),
		"org_id":          envvar.GetTestOrgFromEnv(t),
		"description":     "Updated description",
		"display_name":    "Updated Display Name",
		"random_suffix":   randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		ExternalProviders: map[string]resource.ExternalProvider{
			"time": {},
		},
		CheckDestroy: testAccCheckObservabilityLinkDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccObservabilityLink_observabilityLinkBasicExample(context),
			},
			{
				ResourceName:            "google_observability_link.link",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"bucket", "dataset", "link_id", "location"},
			},
			{
				ResourceName:       "google_observability_link.link",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
			{
				Config: testAccObservabilityLink_observabilityLinkBasicExample(context_1),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction("google_observability_link.link", plancheck.ResourceActionUpdate),
					},
				},
			},
			{
				ResourceName:            "google_observability_link.link",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"bucket", "dataset", "link_id", "location"},
			},
			{
				ResourceName:       "google_observability_link.link",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
		},
	})
}

func testAccObservabilityLink_observabilityLinkBasicExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_project" "project" {
  provider        = "google-beta"
  project_id      = "tf-test%{random_suffix}"
  name            = "tf-test%{random_suffix}"
  org_id          = "%{org_id}"
  billing_account = "%{billing_account}"
  deletion_policy = "DELETE"
}

resource "google_project_service" "observability_api" {
  provider           = "google-beta"
  project            = google_project.project.project_id
  service            = "observability.googleapis.com"
  disable_on_destroy = false
}

# Explicitly chain service enablement to ensure deterministic sequential execution in VCR testing
resource "google_project_service" "bigquery_api" {
  provider           = "google-beta"
  project            = google_project.project.project_id
  service            = "bigquery.googleapis.com"
  disable_on_destroy = false

  depends_on = [
    google_project_service.observability_api
  ]
}

# Actively force the creation of the Service Agent identity
resource "google_project_service_identity" "observability_sa" {
  provider = "google-beta"
  project  = google_project.project.project_id
  service  = "observability.googleapis.com"

  depends_on = [
    google_project_service.observability_api
  ]
}

# Short buffer for the new identity to propagate to global IAM indexes
resource "time_sleep" "wait_for_sa_propagation" {
  create_duration = "30s"
  depends_on      = [
    google_project_service_identity.observability_sa
  ]
}

resource "google_project_iam_member" "observability_sa_service_agent" {
  provider = "google-beta"
  project  = google_project.project.project_id
  role     = "roles/observability.serviceAgent"
  member   = "serviceAccount:${google_project_service_identity.observability_sa.email}"

  depends_on = [
    time_sleep.wait_for_sa_propagation
  ]
}

resource "google_observability_bucket" "bucket" {
  provider     = "google-beta"
  bucket_id    = "_Trace"
  location     = "us-east1"
  project      = google_project.project.project_id
  display_name = "Bucket for Link"
  description  = "Bucket for Link Test"

  depends_on = [
    google_project_iam_member.observability_sa_service_agent
  ]
}

resource "google_observability_link" "link" {
  provider     = "google-beta"
  bucket       = google_observability_bucket.bucket.bucket_id
  dataset      = "Spans"
  location     = "us-east1"
  project      = google_project.project.project_id
  link_id      = "my_link"
  display_name = "%{display_name}"
  description  = "%{description}"

  depends_on = [
    google_project_iam_member.observability_sa_service_agent,
    google_project_service.bigquery_api,
  ]
}
`, context)
}

func testAccCheckObservabilityLinkDestroyProducer(t *testing.T) func(s *terraform.State) error {
	return func(s *terraform.State) error {
		for name, rs := range s.RootModule().Resources {
			if rs.Type != "google_observability_link" {
				continue
			}
			if strings.HasPrefix(name, "data.") {
				continue
			}

			config := acctest.GoogleProviderConfig(t)
			url, err := tpgresource.ReplaceVarsForTest(config, rs, transport_tpg.BaseUrl(observability.Product, config)+"projects/{{project}}/locations/{{location}}/buckets/{{bucket}}/datasets/{{dataset}}/links/{{link_id}}")
			if err != nil {
				return err
			}

			billingProject := ""

			if config.BillingProject != "" {
				billingProject = config.BillingProject
			}

			_, err = transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
				Config:    config,
				Method:    "GET",
				Project:   billingProject,
				RawURL:    url,
				UserAgent: config.UserAgent,
			})
			if err == nil {
				return fmt.Errorf("ObservabilityLink still exists at %s", url)
			}
		}

		return nil
	}
}
