// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/cloudsecuritycompliance/CloudControl.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/resource_custom.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package cloudsecuritycompliance

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"net/url"
	"reflect"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"

	"runtime"

	"github.com/gammazero/workerpool"
	"github.com/hashicorp/errwrap"
	"github.com/hashicorp/go-cty/cty"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/id"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/logging"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/structure"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/registry"
	rmClient "github.com/hashicorp/terraform-provider-google-beta/google-beta/services/resourcemanager/client"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/services/resourcemanagerv3"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/verify"

	bigtableadmin "google.golang.org/api/bigtableadmin/v2"
	"google.golang.org/api/googleapi"
)

var (
	_ = &bigtableadmin.Service{}
	_ = tftypes.Value{}
	_ = url.QueryUnescape
	_ = rmClient.NewClient
	_ = resourcemanagerv3.NewClient
	_ = bytes.Clone
	_ = context.WithCancel
	_ = base64.NewDecoder
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = log.Print
	_ = http.Get
	_ = reflect.ValueOf
	_ = regexp.Match
	_ = slices.Min([]int{1})
	_ = sort.IntSlice{}
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = runtime.GOARCH
	_ = workerpool.New
	_ = errwrap.Wrap
	_ = cty.BoolVal
	_ = diag.Diagnostic{}
	_ = customdiff.All
	_ = id.UniqueId
	_ = logging.LogLevel
	_ = retry.Retry
	_ = schema.Noop
	_ = validation.All
	_ = structure.ExpandJsonFromString
	_ = terraform.State{}
	_ = registry.Schema{}
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = verify.ValidateEnum
	_ = googleapi.Error{}
)

func resourceCloudSecurityComplianceCloudControlCustomImport(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	config := meta.(*transport_tpg.Config)
	if err := tpgresource.ParseImportId([]string{
		"^(?P<parent>.*)/locations/(?P<location>[^/]+)/cloudControls/(?P<cloud_control_id>[^/]+)$",
		"^organizations/(?P<organization>[^/]+)/locations/(?P<location>[^/]+)/cloudControls/(?P<cloud_control_id>[^/]+)$",
	}, d, config); err != nil {
		return nil, err
	}

	// Seamlessly map the overlapping parameters
	if d.Get("organization").(string) == "" && d.Get("parent").(string) != "" {
		if strings.HasPrefix(d.Get("parent").(string), "organizations/") {
			d.Set("organization", strings.TrimPrefix(d.Get("parent").(string), "organizations/"))
		}
	} else if d.Get("parent").(string) == "" && d.Get("organization").(string) != "" {
		d.Set("parent", "organizations/"+d.Get("organization").(string))
	}

	// Manually construct the ID without relying on the identity generator
	id := fmt.Sprintf("%s/locations/%s/cloudControls/%s", d.Get("parent").(string), d.Get("location").(string), d.Get("cloud_control_id").(string))
	d.SetId(id)

	return []*schema.ResourceData{d}, nil
}

func resourceCloudSecurityComplianceCloudControlEncoder(d *schema.ResourceData, meta interface{}, obj map[string]interface{}) (map[string]interface{}, error) {
	// Build the fullname for the CloudControl resource from the provided
	// parent, location and cloud_control_id fields and set it on the
	// API object that will be sent in the request.
	// Extract the parent scope, falling back to organization for backward compatibility
	var parentStr string
	if parent, ok := d.GetOk("parent"); ok && parent.(string) != "" {
		parentStr = parent.(string)
	} else if org, ok := d.GetOk("organization"); ok && org.(string) != "" {
		parentStr = fmt.Sprintf("organizations/%s", org.(string))
	} else {
		return nil, fmt.Errorf("either parent or organization must be provided")
	}
	loc, ok := d.Get("location").(string)
	if !ok || loc == "" {
		return nil, fmt.Errorf("location is required and must be a non-empty string")
	}
	ccid, ok := d.Get("cloud_control_id").(string)
	if !ok || ccid == "" {
		return nil, fmt.Errorf("cloud_control_id is required and must be a non-empty string")
	}
	// Compose the resource name in the expected API format.
	// The parent already includes the resource type (e.g. projects/my-project)
	name := fmt.Sprintf("%s/locations/%s/cloudControls/%s", parentStr, loc, ccid)
	obj["name"] = name
	return obj, nil
}

func identityCloudSecurityComplianceCloudControlResourceV1() tftypes.Type {
	return tftypes.Object{
		AttributeTypes: map[string]tftypes.Type{
			"organization":     tftypes.String,
			"location":         tftypes.String,
			"cloud_control_id": tftypes.String,
		},
	}
}

func IdentityCloudSecurityComplianceCloudControlUpgradeV1(ctx context.Context, rawState map[string]interface{}, meta interface{}) (map[string]interface{}, error) {
	if org, ok := rawState["organization"].(string); ok && org != "" {
		rawState["parent"] = "organizations/" + org
		delete(rawState, "organization")
	}
	return rawState, nil
}
