resource: google_kms_google_kms_autokey_config
generation_type: mmv1
source_file: products/kms/datasource_autokey_config.yaml
api_service_name: cloudkms.googleapis.com
api_version: v1
api_resource_type_kind: google_kms_autokey_config
fields:
    - field: folder
      provider_only: true
    - api_field: keyProject
    - api_field: keyProjectResolutionMode
    - api_field: name
    - field: project
      provider_only: true
