// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package google

import "github.com/hashicorp/terraform/helper/schema"

var LoggingDefaultBasePath = "https://logging.googleapis.com/v2/"

var LoggingBasePathEntry = &schema.Schema{
	Type:     schema.TypeString,
	Optional: true,
	DefaultFunc: schema.MultiEnvDefaultFunc([]string{
		"GOOGLE_LOGGING_BASE_PATH",
	}, LoggingDefaultBasePath),
}

var GeneratedLoggingResourcesMap = map[string]*schema.Resource{
	"google_logging_metric": resourceLoggingMetric(),
}
