// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/config/DeploymentGroup.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/resource.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package config

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"reflect"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/hashicorp/errwrap"
	"github.com/hashicorp/go-cty/cty"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/id"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/logging"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/structure"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/registry"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/verify"

	"google.golang.org/api/googleapi"
)

var (
	_ = bytes.Clone
	_ = context.WithCancel
	_ = base64.NewDecoder
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = log.Print
	_ = http.Get
	_ = reflect.ValueOf
	_ = regexp.Match
	_ = slices.Min([]int{1})
	_ = sort.IntSlice{}
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = errwrap.Wrap
	_ = cty.BoolVal
	_ = diag.Diagnostic{}
	_ = customdiff.All
	_ = id.UniqueId
	_ = logging.LogLevel
	_ = retry.Retry
	_ = schema.Noop
	_ = validation.All
	_ = structure.ExpandJsonFromString
	_ = terraform.State{}
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = verify.ValidateEnum
	_ = googleapi.Error{}
)

func init() {
	registry.Schema{
		Name:        "google_config_deployment_group",
		ProductName: "config",
		Type:        registry.SchemaTypeResource,
		Schema:      ResourceConfigDeploymentGroup(),
	}.Register()
}

func ResourceConfigDeploymentGroup() *schema.Resource {
	return &schema.Resource{
		Create: resourceConfigDeploymentGroupCreate,
		Read:   resourceConfigDeploymentGroupRead,
		Update: resourceConfigDeploymentGroupUpdate,
		Delete: resourceConfigDeploymentGroupDelete,

		Importer: &schema.ResourceImporter{
			State: resourceConfigDeploymentGroupImport,
		},

		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(20 * time.Minute),
			Update: schema.DefaultTimeout(20 * time.Minute),
			Delete: schema.DefaultTimeout(20 * time.Minute),
		},

		CustomizeDiff: customdiff.All(
			tpgresource.SetLabelsDiff,
			tpgresource.SetAnnotationsDiff,
			tpgresource.DefaultProviderProject,
			tpgresource.DefaultProviderDeletionPolicy("DELETE"),
		),

		Identity: &schema.ResourceIdentity{
			Version: 1,
			SchemaFunc: func() map[string]*schema.Schema {
				return map[string]*schema.Schema{
					"name": {
						Type:              schema.TypeString,
						RequiredForImport: true,
					},
					"location": {
						Type:              schema.TypeString,
						RequiredForImport: true,
					},
					"project": {
						Type:              schema.TypeString,
						OptionalForImport: true,
					},
				}
			},
		},
		ResourceBehavior: schema.ResourceBehavior{
			MutableIdentity: true,
		},

		Schema: map[string]*schema.Schema{
			"location": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: `The location for the resource`,
			},
			"name": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: `The user-specified ID of the deployment group.`,
			},
			"annotations": {
				Type:     schema.TypeMap,
				Optional: true,
				Description: `Arbitrary key-value metadata storage.

**Note**: This field is non-authoritative, and will only manage the annotations present in your configuration.
Please refer to the field 'effective_annotations' for all of the annotations present on the resource.`,
				Elem: &schema.Schema{Type: schema.TypeString},
			},
			"deployment_units": {
				Type:     schema.TypeList,
				Optional: true,
				Description: `The deployment units of the deployment group in a DAG like structure.
When a deployment group is being provisioned, the deployment units are
deployed in a DAG order.
The provided units must be in a DAG order, otherwise an error will be
returned.`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:        schema.TypeString,
							Required:    true,
							Description: `The id of the deployment unit. Must be unique within the deployment group.`,
						},
						"dependencies": {
							Type:     schema.TypeList,
							Optional: true,
							Description: `The IDs of the deployment units within the deployment group that this
unit depends on.`,
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
						"deployment": {
							Type:     schema.TypeString,
							Optional: true,
							Description: `The name of the deployment to be provisioned.
Format:
'projects/{project_id}/locations/{location}/deployments/{deployment}'.`,
						},
					},
				},
			},
			"labels": {
				Type:     schema.TypeMap,
				Optional: true,
				Description: `User-defined metadata for the deployment group.

**Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
Please refer to the field 'effective_labels' for all of the labels present on the resource.`,
				Elem: &schema.Schema{Type: schema.TypeString},
			},
			"create_time": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `Output only. Time when the deployment group was created.`,
			},
			"effective_annotations": {
				Type:        schema.TypeMap,
				Computed:    true,
				Description: `All of annotations (key/value pairs) present on the resource in GCP, including the annotations configured through Terraform, other clients and services.`,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"effective_labels": {
				Type:        schema.TypeMap,
				Computed:    true,
				Description: `All of labels (key/value pairs) present on the resource in GCP, including the labels configured through Terraform, other clients and services.`,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"provisioning_state": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `The provisioning state of the deployment group.`,
			},
			"provisioning_state_description": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `Additional information regarding the current provisioning state.`,
			},
			"state": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `Current state of the deployment group.`,
			},
			"state_description": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `Additional information regarding the current state.`,
			},
			"terraform_labels": {
				Type:     schema.TypeMap,
				Computed: true,
				Description: `The combination of labels configured directly on the resource
 and default labels configured on the provider.`,
				Elem: &schema.Schema{Type: schema.TypeString},
			},
			"update_time": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `Output only. Time when the deployment group was last updated.`,
			},
			"deployment_reference_policy": {
				Type:         schema.TypeString,
				Optional:     true,
				ValidateFunc: verify.ValidateEnum([]string{"DEPLOYMENT_REFERENCE_POLICY_UNSPECIFIED", "FAIL_IF_ANY_REFERENCES_EXIST", "FAIL_IF_METADATA_REFERENCES_EXIST", "IGNORE_DEPLOYMENT_REFERENCES", ""}),
				Description:  `Policy on how to handle referenced deployments when deleting the DeploymentGroup. Default value: "IGNORE_DEPLOYMENT_REFERENCES" Possible values: ["DEPLOYMENT_REFERENCE_POLICY_UNSPECIFIED", "FAIL_IF_ANY_REFERENCES_EXIST", "FAIL_IF_METADATA_REFERENCES_EXIST", "IGNORE_DEPLOYMENT_REFERENCES"]`,
				Default:      "IGNORE_DEPLOYMENT_REFERENCES",
			},
			"force_destroy": {
				Type:     schema.TypeBool,
				Optional: true,
				Description: `If set to true, any revisions for this deployment group will also be deleted.
(Otherwise, the request will only work if the deployment group has no revisions.)`,
				Default: false,
			},
			"project": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
				ForceNew: true,
			},
			"deletion_policy": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
				Description: `Whether Terraform will be prevented from destroying the instance. Defaults to "DELETE".
When a 'terraform destroy' or 'terraform apply' would delete the instance,
the command will fail if this field is set to "PREVENT" in Terraform state.
When set to "ABANDON", the command will remove the resource from Terraform
management without updating or deleting the resource in the API.
When set to "DELETE", deleting the resource is allowed.
`,
			},
		},
		UseJSONNumber: true,
	}
}

func resourceConfigDeploymentGroupCreate(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	obj := make(map[string]interface{})
	deploymentUnitsProp, err := expandConfigDeploymentGroupDeploymentUnits(d.Get("deployment_units"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("deployment_units"); !tpgresource.IsEmptyValue(reflect.ValueOf(deploymentUnitsProp)) && (ok || !reflect.DeepEqual(v, deploymentUnitsProp)) {
		obj["deploymentUnits"] = deploymentUnitsProp
	}
	effectiveLabelsProp, err := expandConfigDeploymentGroupEffectiveLabels(d.Get("effective_labels"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("effective_labels"); !tpgresource.IsEmptyValue(reflect.ValueOf(effectiveLabelsProp)) && (ok || !reflect.DeepEqual(v, effectiveLabelsProp)) {
		obj["labels"] = effectiveLabelsProp
	}
	effectiveAnnotationsProp, err := expandConfigDeploymentGroupEffectiveAnnotations(d.Get("effective_annotations"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("effective_annotations"); !tpgresource.IsEmptyValue(reflect.ValueOf(effectiveAnnotationsProp)) && (ok || !reflect.DeepEqual(v, effectiveAnnotationsProp)) {
		obj["annotations"] = effectiveAnnotationsProp
	}

	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/deploymentGroups?deploymentGroupId={{name}}")
	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Creating new DeploymentGroup: %#v", obj)
	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for DeploymentGroup: %s", err)
	}
	billingProject = project

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "POST",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
		Timeout:   d.Timeout(schema.TimeoutCreate),
		Headers:   headers,
	})
	if err != nil {
		return fmt.Errorf("Error creating DeploymentGroup: %s", err)
	}

	// Store the ID now
	id, err := tpgresource.ReplaceVars(d, config, "projects/{{project}}/locations/{{location}}/deploymentGroups/{{name}}")
	if err != nil {
		return fmt.Errorf("Error constructing id: %s", err)
	}
	d.SetId(id)

	err = ConfigOperationWaitTime(
		config, res, project, "Creating DeploymentGroup", userAgent,
		d.Timeout(schema.TimeoutCreate))

	if err != nil {
		// The resource didn't actually create
		d.SetId("")
		return fmt.Errorf("Error waiting to create DeploymentGroup: %s", err)
	}

	log.Printf("[DEBUG] Finished creating DeploymentGroup %q: %#v", d.Id(), res)

	identity, err := d.Identity()
	if err == nil && identity != nil {
		if nameValue, ok := d.GetOk("name"); ok && nameValue.(string) != "" {
			if err = identity.Set("name", nameValue.(string)); err != nil {
				return fmt.Errorf("Error setting name: %s", err)
			}
		}
		if locationValue, ok := d.GetOk("location"); ok && locationValue.(string) != "" {
			if err = identity.Set("location", locationValue.(string)); err != nil {
				return fmt.Errorf("Error setting location: %s", err)
			}
		}
		if projectValue, ok := d.GetOk("project"); ok && projectValue.(string) != "" {
			if err = identity.Set("project", projectValue.(string)); err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Create) identity not set: %s", err)
	}

	return resourceConfigDeploymentGroupRead(d, meta)
}

func resourceConfigDeploymentGroupRead(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/deploymentGroups/{{name}}")
	if err != nil {
		return err
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for DeploymentGroup: %s", err)
	}
	billingProject = project

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "GET",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Headers:   headers,
	})
	if err != nil {
		return transport_tpg.HandleNotFoundError(err, d, fmt.Sprintf("ConfigDeploymentGroup %q", d.Id()))
	}

	log.Printf("[DEBUG] Finished reading ConfigDeploymentGroup %q: %#v", d.Id(), res)

	// Explicitly set virtual fields to default values if unset
	if _, ok := d.GetOkExists("deployment_reference_policy"); !ok {
		if err := d.Set("deployment_reference_policy", "IGNORE_DEPLOYMENT_REFERENCES"); err != nil {
			return fmt.Errorf("Error setting deployment_reference_policy: %s", err)
		}
	}
	if _, ok := d.GetOkExists("force_destroy"); !ok {
		if err := d.Set("force_destroy", false); err != nil {
			return fmt.Errorf("Error setting force_destroy: %s", err)
		}
	}
	if _, ok := d.GetOkExists("deletion_policy"); !ok {
		//prioritize config's value if present
		if config.DeletionPolicy != "" {
			if err := d.Set("deletion_policy", config.DeletionPolicy); err != nil {
				return fmt.Errorf("Error setting deletion_policy: %s", err)
			}
		} else {
			if err := d.Set("deletion_policy", "DELETE"); err != nil {
				return fmt.Errorf("Error setting deletion_policy: %s", err)
			}
		}
	}
	if err := d.Set("project", project); err != nil {
		return fmt.Errorf("Error reading DeploymentGroup: %s", err)
	}

	err = ResourceConfigDeploymentGroupFlatten(d, meta, res, config, project, userAgent, billingProject, url, headers)
	if err != nil {
		return err
	}

	identity, err := d.Identity()
	if err == nil && identity != nil {
		if v, ok := identity.GetOk("name"); !ok && v == "" {
			err = identity.Set("name", d.Get("name").(string))
			if err != nil {
				return fmt.Errorf("Error setting name: %s", err)
			}
		}
		if v, ok := identity.GetOk("location"); !ok && v == "" {
			err = identity.Set("location", d.Get("location").(string))
			if err != nil {
				return fmt.Errorf("Error setting location: %s", err)
			}
		}
		if v, ok := identity.GetOk("project"); !ok && v == "" {
			err = identity.Set("project", d.Get("project").(string))
			if err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Read) identity not set: %s", err)
	}

	return nil
}

func resourceConfigDeploymentGroupUpdate(d *schema.ResourceData, meta interface{}) error {
	clientSideFields := map[string]bool{"deletion_policy": true}
	clientSideOnly := true
	for field := range ResourceConfigDeploymentGroup().Schema {
		if d.HasChange(field) && !clientSideFields[field] {
			clientSideOnly = false
			break
		}
	}
	if clientSideOnly {
		log.Print("[DEBUG] Only client-side changes detected. Cancelling update operation.")
		return resourceConfigDeploymentGroupRead(d, meta)
	}

	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}
	identity, err := d.Identity()
	if err == nil && identity != nil {
		if nameValue, ok := d.GetOk("name"); ok && nameValue.(string) != "" {
			if err = identity.Set("name", nameValue.(string)); err != nil {
				return fmt.Errorf("Error setting name: %s", err)
			}
		}
		if locationValue, ok := d.GetOk("location"); ok && locationValue.(string) != "" {
			if err = identity.Set("location", locationValue.(string)); err != nil {
				return fmt.Errorf("Error setting location: %s", err)
			}
		}
		if projectValue, ok := d.GetOk("project"); ok && projectValue.(string) != "" {
			if err = identity.Set("project", projectValue.(string)); err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Update) identity not set: %s", err)
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for DeploymentGroup: %s", err)
	}
	billingProject = project

	obj := make(map[string]interface{})
	deploymentUnitsProp, err := expandConfigDeploymentGroupDeploymentUnits(d.Get("deployment_units"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("deployment_units"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, deploymentUnitsProp)) {
		obj["deploymentUnits"] = deploymentUnitsProp
	}
	effectiveLabelsProp, err := expandConfigDeploymentGroupEffectiveLabels(d.Get("effective_labels"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("effective_labels"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, effectiveLabelsProp)) {
		obj["labels"] = effectiveLabelsProp
	}
	effectiveAnnotationsProp, err := expandConfigDeploymentGroupEffectiveAnnotations(d.Get("effective_annotations"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("effective_annotations"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, effectiveAnnotationsProp)) {
		obj["annotations"] = effectiveAnnotationsProp
	}

	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/deploymentGroups/{{name}}")
	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Updating DeploymentGroup %q: %#v", d.Id(), obj)
	headers := make(http.Header)
	updateMask := []string{}

	if d.HasChange("deployment_units") {
		updateMask = append(updateMask, "deploymentUnits")
	}

	if d.HasChange("effective_labels") {
		updateMask = append(updateMask, "labels")
	}

	if d.HasChange("effective_annotations") {
		updateMask = append(updateMask, "annotations")
	}
	// updateMask is a URL parameter but not present in the schema, so ReplaceVars
	// won't set it
	url, err = transport_tpg.AddQueryParams(url, map[string]string{"updateMask": strings.Join(updateMask, ",")})
	if err != nil {
		return err
	}

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	// if updateMask is empty we are not updating anything so skip the post
	if len(updateMask) > 0 {
		res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
			Config:    config,
			Method:    "PATCH",
			Project:   billingProject,
			RawURL:    url,
			UserAgent: userAgent,
			Body:      obj,
			Timeout:   d.Timeout(schema.TimeoutUpdate),
			Headers:   headers,
		})

		if err != nil {
			return fmt.Errorf("Error updating DeploymentGroup %q: %s", d.Id(), err)
		} else {
			log.Printf("[DEBUG] Finished updating DeploymentGroup %q: %#v", d.Id(), res)
		}

		err = ConfigOperationWaitTime(
			config, res, project, "Updating DeploymentGroup", userAgent,
			d.Timeout(schema.TimeoutUpdate))

		if err != nil {
			return err
		}
	}

	return resourceConfigDeploymentGroupRead(d, meta)
}

func resourceConfigDeploymentGroupDelete(d *schema.ResourceData, meta interface{}) error {
	if d.Get("deletion_policy").(string) == "PREVENT" {
		return fmt.Errorf("cannot destroy ConfigDeploymentGroup without setting deletion_policy=\"DELETE\" and running `terraform apply`")
	}
	if d.Get("deletion_policy").(string) == "ABANDON" {
		log.Printf("[DEBUG] deletion_policy set to \"ABANDON\", removing DeploymentGroup %q from Terraform state without deletion", d.Id())
		return nil
	}
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for DeploymentGroup: %s", err)
	}
	billingProject = project
	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/deploymentGroups/{{name}}?deploymentReferencePolicy={{deployment_reference_policy}}&force={{force_destroy}}")
	if err != nil {
		return err
	}

	var obj map[string]interface{}

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)

	log.Printf("[DEBUG] Deleting DeploymentGroup %q", d.Id())
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "DELETE",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
		Timeout:   d.Timeout(schema.TimeoutDelete),
		Headers:   headers,
	})
	if err != nil {
		return transport_tpg.HandleNotFoundError(err, d, "DeploymentGroup")
	}

	err = ConfigOperationWaitTime(
		config, res, project, "Deleting DeploymentGroup", userAgent,
		d.Timeout(schema.TimeoutDelete))

	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Finished deleting DeploymentGroup %q: %#v", d.Id(), res)
	return nil
}

func resourceConfigDeploymentGroupImport(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	config := meta.(*transport_tpg.Config)
	if err := tpgresource.ParseImportId([]string{
		"^projects/(?P<project>[^/]+)/locations/(?P<location>[^/]+)/deploymentGroups/(?P<name>[^/]+)$",
		"^(?P<project>[^/]+)/(?P<location>[^/]+)/(?P<name>[^/]+)$",
		"^(?P<location>[^/]+)/(?P<name>[^/]+)$",
	}, d, config); err != nil {
		return nil, err
	}

	// Replace import id for the resource id
	id, err := tpgresource.ReplaceVars(d, config, "projects/{{project}}/locations/{{location}}/deploymentGroups/{{name}}")
	if err != nil {
		return nil, fmt.Errorf("Error constructing id: %s", err)
	}
	d.SetId(id)

	// Explicitly set virtual fields to default values on import
	if err := d.Set("deployment_reference_policy", "IGNORE_DEPLOYMENT_REFERENCES"); err != nil {
		return nil, fmt.Errorf("Error setting deployment_reference_policy: %s", err)
	}
	if err := d.Set("force_destroy", false); err != nil {
		return nil, fmt.Errorf("Error setting force_destroy: %s", err)
	}

	return []*schema.ResourceData{d}, nil
}

func flattenConfigDeploymentGroupDeploymentUnits(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}
	l := v.([]interface{})
	transformed := make([]interface{}, 0, len(l))
	for i, raw := range l {
		_ = i
		original := raw.(map[string]interface{})
		if len(original) < 1 {
			// Do not include empty json objects coming back from the api
			continue
		}
		transformed = append(transformed, map[string]interface{}{
			"id":           flattenConfigDeploymentGroupDeploymentUnitsId(original["id"], d, config),
			"dependencies": flattenConfigDeploymentGroupDeploymentUnitsDependencies(original["dependencies"], d, config),
			"deployment":   flattenConfigDeploymentGroupDeploymentUnitsDeployment(original["deployment"], d, config),
		})
	}
	return transformed
}
func flattenConfigDeploymentGroupDeploymentUnitsId(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenConfigDeploymentGroupDeploymentUnitsDependencies(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenConfigDeploymentGroupDeploymentUnitsDeployment(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenConfigDeploymentGroupLabels(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}

	transformed := make(map[string]interface{})
	if l, ok := d.GetOkExists("labels"); ok {
		for k := range l.(map[string]interface{}) {
			transformed[k] = v.(map[string]interface{})[k]
		}
	}

	return transformed
}

func flattenConfigDeploymentGroupAnnotations(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}

	transformed := make(map[string]interface{})
	if l, ok := d.GetOkExists("annotations"); ok {
		for k := range l.(map[string]interface{}) {
			transformed[k] = v.(map[string]interface{})[k]
		}
	}

	return transformed
}

func flattenConfigDeploymentGroupCreateTime(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenConfigDeploymentGroupUpdateTime(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenConfigDeploymentGroupState(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenConfigDeploymentGroupStateDescription(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenConfigDeploymentGroupProvisioningState(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenConfigDeploymentGroupProvisioningStateDescription(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenConfigDeploymentGroupTerraformLabels(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}

	transformed := make(map[string]interface{})
	if l, ok := d.GetOkExists("terraform_labels"); ok {
		for k := range l.(map[string]interface{}) {
			transformed[k] = v.(map[string]interface{})[k]
		}
	}

	return transformed
}

func flattenConfigDeploymentGroupEffectiveLabels(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenConfigDeploymentGroupEffectiveAnnotations(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func expandConfigDeploymentGroupDeploymentUnits(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	if v == nil {
		return nil, nil
	}
	l := v.([]interface{})
	req := make([]interface{}, 0, len(l))
	for _, raw := range l {
		if raw == nil {
			continue
		}
		original := raw.(map[string]interface{})
		transformed := make(map[string]interface{})

		transformedId, err := expandConfigDeploymentGroupDeploymentUnitsId(original["id"], d, config)
		if err != nil {
			return nil, err
		} else if val := reflect.ValueOf(transformedId); val.IsValid() && !tpgresource.IsEmptyValue(val) {
			transformed["id"] = transformedId
		}

		transformedDependencies, err := expandConfigDeploymentGroupDeploymentUnitsDependencies(original["dependencies"], d, config)
		if err != nil {
			return nil, err
		} else if val := reflect.ValueOf(transformedDependencies); val.IsValid() && !tpgresource.IsEmptyValue(val) {
			transformed["dependencies"] = transformedDependencies
		}

		transformedDeployment, err := expandConfigDeploymentGroupDeploymentUnitsDeployment(original["deployment"], d, config)
		if err != nil {
			return nil, err
		} else if val := reflect.ValueOf(transformedDeployment); val.IsValid() && !tpgresource.IsEmptyValue(val) {
			transformed["deployment"] = transformedDeployment
		}

		req = append(req, transformed)
	}
	return req, nil
}

func expandConfigDeploymentGroupDeploymentUnitsId(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandConfigDeploymentGroupDeploymentUnitsDependencies(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandConfigDeploymentGroupDeploymentUnitsDeployment(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandConfigDeploymentGroupEffectiveLabels(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (map[string]string, error) {
	if v == nil {
		return map[string]string{}, nil
	}
	m := make(map[string]string)
	for k, val := range v.(map[string]interface{}) {
		m[k] = val.(string)
	}
	return m, nil
}

func expandConfigDeploymentGroupEffectiveAnnotations(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (map[string]string, error) {
	if v == nil {
		return map[string]string{}, nil
	}
	m := make(map[string]string)
	for k, val := range v.(map[string]interface{}) {
		m[k] = val.(string)
	}
	return m, nil
}

func ResourceConfigDeploymentGroupFlatten(d *schema.ResourceData, meta interface{}, res map[string]interface{}, config *transport_tpg.Config, project string, userAgent string, billingProject string, url string, headers http.Header) error {
	var err error

	if err = d.Set("deployment_units", flattenConfigDeploymentGroupDeploymentUnits(res["deploymentUnits"], d, config)); err != nil {
		return fmt.Errorf("Error reading DeploymentGroup: %s", err)
	}
	if err = d.Set("labels", flattenConfigDeploymentGroupLabels(res["labels"], d, config)); err != nil {
		return fmt.Errorf("Error reading DeploymentGroup: %s", err)
	}
	if err = d.Set("annotations", flattenConfigDeploymentGroupAnnotations(res["annotations"], d, config)); err != nil {
		return fmt.Errorf("Error reading DeploymentGroup: %s", err)
	}
	if err = d.Set("create_time", flattenConfigDeploymentGroupCreateTime(res["createTime"], d, config)); err != nil {
		return fmt.Errorf("Error reading DeploymentGroup: %s", err)
	}
	if err = d.Set("update_time", flattenConfigDeploymentGroupUpdateTime(res["updateTime"], d, config)); err != nil {
		return fmt.Errorf("Error reading DeploymentGroup: %s", err)
	}
	if err = d.Set("state", flattenConfigDeploymentGroupState(res["state"], d, config)); err != nil {
		return fmt.Errorf("Error reading DeploymentGroup: %s", err)
	}
	if err = d.Set("state_description", flattenConfigDeploymentGroupStateDescription(res["stateDescription"], d, config)); err != nil {
		return fmt.Errorf("Error reading DeploymentGroup: %s", err)
	}
	if err = d.Set("provisioning_state", flattenConfigDeploymentGroupProvisioningState(res["provisioningState"], d, config)); err != nil {
		return fmt.Errorf("Error reading DeploymentGroup: %s", err)
	}
	if err = d.Set("provisioning_state_description", flattenConfigDeploymentGroupProvisioningStateDescription(res["provisioningStateDescription"], d, config)); err != nil {
		return fmt.Errorf("Error reading DeploymentGroup: %s", err)
	}
	if err = d.Set("terraform_labels", flattenConfigDeploymentGroupTerraformLabels(res["labels"], d, config)); err != nil {
		return fmt.Errorf("Error reading DeploymentGroup: %s", err)
	}
	if err = d.Set("effective_labels", flattenConfigDeploymentGroupEffectiveLabels(res["labels"], d, config)); err != nil {
		return fmt.Errorf("Error reading DeploymentGroup: %s", err)
	}
	if err = d.Set("effective_annotations", flattenConfigDeploymentGroupEffectiveAnnotations(res["annotations"], d, config)); err != nil {
		return fmt.Errorf("Error reading DeploymentGroup: %s", err)
	}

	return nil
}
