// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/agentregistry/McpServer.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/resource.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package agentregistry

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"reflect"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/hashicorp/errwrap"
	"github.com/hashicorp/go-cty/cty"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/id"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/logging"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/structure"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/registry"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/verify"

	"google.golang.org/api/googleapi"
)

var (
	_ = bytes.Clone
	_ = context.WithCancel
	_ = base64.NewDecoder
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = log.Print
	_ = http.Get
	_ = reflect.ValueOf
	_ = regexp.Match
	_ = slices.Min([]int{1})
	_ = sort.IntSlice{}
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = errwrap.Wrap
	_ = cty.BoolVal
	_ = diag.Diagnostic{}
	_ = customdiff.All
	_ = id.UniqueId
	_ = logging.LogLevel
	_ = retry.Retry
	_ = schema.Noop
	_ = validation.All
	_ = structure.ExpandJsonFromString
	_ = terraform.State{}
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = verify.ValidateEnum
	_ = googleapi.Error{}
)

func init() {
	registry.Schema{
		Name:        "google_agent_registry_mcp_server",
		ProductName: "agentregistry",
		Type:        registry.SchemaTypeResource,
		Schema:      ResourceAgentRegistryMcpServer(),
	}.Register()
}

func ResourceAgentRegistryMcpServer() *schema.Resource {
	return &schema.Resource{
		Create: resourceAgentRegistryMcpServerCreate,
		Read:   resourceAgentRegistryMcpServerRead,
		Update: resourceAgentRegistryMcpServerUpdate,
		Delete: resourceAgentRegistryMcpServerDelete,

		Importer: &schema.ResourceImporter{
			State: resourceAgentRegistryMcpServerImport,
		},

		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(20 * time.Minute),
			Update: schema.DefaultTimeout(20 * time.Minute),
			Delete: schema.DefaultTimeout(20 * time.Minute),
		},

		CustomizeDiff: customdiff.All(
			tpgresource.DefaultProviderProject,
			tpgresource.DefaultProviderDeletionPolicy("DELETE"),
		),

		Identity: &schema.ResourceIdentity{
			Version: 1,
			SchemaFunc: func() map[string]*schema.Schema {
				return map[string]*schema.Schema{
					"location": {
						Type:              schema.TypeString,
						RequiredForImport: true,
					},
					"mcp_server_id": {
						Type:              schema.TypeString,
						RequiredForImport: true,
					},
					"project": {
						Type:              schema.TypeString,
						OptionalForImport: true,
					},
				}
			},
		},
		ResourceBehavior: schema.ResourceBehavior{
			MutableIdentity: true,
		},

		Schema: map[string]*schema.Schema{
			"location": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: `The location of the Agent Registry service.`,
			},
			"mcp_server_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: `The ID to use for the MCP Server service.`,
			},
			"mcp_server_spec": {
				Type:        schema.TypeList,
				Required:    true,
				Description: `The specification of the MCP Server.`,
				MaxItems:    1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"type": {
							Type:         schema.TypeString,
							Required:     true,
							ValidateFunc: verify.ValidateEnum([]string{"TYPE_UNSPECIFIED", "NO_SPEC", "TOOL_SPEC"}),
							Description:  `The type of the MCP Server spec content. Possible values: ["TYPE_UNSPECIFIED", "NO_SPEC", "TOOL_SPEC"]`,
						},
						"content": {
							Type:         schema.TypeString,
							Optional:     true,
							ValidateFunc: validation.StringIsJSON,
							StateFunc:    func(v interface{}) string { s, _ := structure.NormalizeJsonString(v); return s },
							Description:  `Optional. The content of the MCP Server spec.`,
						},
					},
				},
			},
			"description": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: `User-defined description of the MCP Server.`,
			},
			"display_name": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: `User-defined display name for the MCP Server.`,
			},
			"interfaces": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: `The connection details for the MCP Server.`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"protocol_binding": {
							Type:         schema.TypeString,
							Required:     true,
							ValidateFunc: verify.ValidateEnum([]string{"PROTOCOL_BINDING_UNSPECIFIED", "JSONRPC", "GRPC", "HTTP_JSON"}),
							Description:  `The transport protocol binding. Possible values: ["PROTOCOL_BINDING_UNSPECIFIED", "JSONRPC", "GRPC", "HTTP_JSON"]`,
						},
						"url": {
							Type:        schema.TypeString,
							Required:    true,
							Description: `The destination URL.`,
						},
					},
				},
			},
			"create_time": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `Output only. The creation timestamp.`,
			},
			"name": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `Output only. The resource name of the MCP Server.`,
			},
			"registry_resource": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `Output only. The resource name of the resulting MCP Server.`,
			},
			"update_time": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `Output only. The update timestamp.`,
			},
			"project": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
				ForceNew: true,
			},
			"deletion_policy": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
				Description: `Whether Terraform will be prevented from destroying the instance. Defaults to "DELETE".
When a 'terraform destroy' or 'terraform apply' would delete the instance,
the command will fail if this field is set to "PREVENT" in Terraform state.
When set to "ABANDON", the command will remove the resource from Terraform
management without updating or deleting the resource in the API.
When set to "DELETE", deleting the resource is allowed.
`,
			},
		},
		UseJSONNumber: true,
	}
}

func resourceAgentRegistryMcpServerCreate(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	obj := make(map[string]interface{})
	displayNameProp, err := expandAgentRegistryMcpServerDisplayName(d.Get("display_name"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("display_name"); !tpgresource.IsEmptyValue(reflect.ValueOf(displayNameProp)) && (ok || !reflect.DeepEqual(v, displayNameProp)) {
		obj["displayName"] = displayNameProp
	}
	descriptionProp, err := expandAgentRegistryMcpServerDescription(d.Get("description"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("description"); !tpgresource.IsEmptyValue(reflect.ValueOf(descriptionProp)) && (ok || !reflect.DeepEqual(v, descriptionProp)) {
		obj["description"] = descriptionProp
	}
	interfacesProp, err := expandAgentRegistryMcpServerInterfaces(d.Get("interfaces"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("interfaces"); !tpgresource.IsEmptyValue(reflect.ValueOf(interfacesProp)) && (ok || !reflect.DeepEqual(v, interfacesProp)) {
		obj["interfaces"] = interfacesProp
	}
	mcpServerSpecProp, err := expandAgentRegistryMcpServerMcpServerSpec(d.Get("mcp_server_spec"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("mcp_server_spec"); !tpgresource.IsEmptyValue(reflect.ValueOf(mcpServerSpecProp)) && (ok || !reflect.DeepEqual(v, mcpServerSpecProp)) {
		obj["mcpServerSpec"] = mcpServerSpecProp
	}

	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/services?serviceId={{mcp_server_id}}")
	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Creating new McpServer: %#v", obj)
	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for McpServer: %s", err)
	}
	billingProject = project

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "POST",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
		Timeout:   d.Timeout(schema.TimeoutCreate),
		Headers:   headers,
	})
	if err != nil {
		return fmt.Errorf("Error creating McpServer: %s", err)
	}

	// Store the ID now
	id, err := tpgresource.ReplaceVars(d, config, "projects/{{project}}/locations/{{location}}/services/{{mcp_server_id}}")
	if err != nil {
		return fmt.Errorf("Error constructing id: %s", err)
	}
	d.SetId(id)

	err = AgentRegistryOperationWaitTime(
		config, res, project, "Creating McpServer", userAgent,
		d.Timeout(schema.TimeoutCreate))

	if err != nil {
		// The resource didn't actually create
		d.SetId("")
		return fmt.Errorf("Error waiting to create McpServer: %s", err)
	}

	log.Printf("[DEBUG] Finished creating McpServer %q: %#v", d.Id(), res)

	identity, err := d.Identity()
	if err == nil && identity != nil {
		if locationValue, ok := d.GetOk("location"); ok && locationValue.(string) != "" {
			if err = identity.Set("location", locationValue.(string)); err != nil {
				return fmt.Errorf("Error setting location: %s", err)
			}
		}
		if mcpServerIdValue, ok := d.GetOk("mcp_server_id"); ok && mcpServerIdValue.(string) != "" {
			if err = identity.Set("mcp_server_id", mcpServerIdValue.(string)); err != nil {
				return fmt.Errorf("Error setting mcp_server_id: %s", err)
			}
		}
		if projectValue, ok := d.GetOk("project"); ok && projectValue.(string) != "" {
			if err = identity.Set("project", projectValue.(string)); err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Create) identity not set: %s", err)
	}

	return resourceAgentRegistryMcpServerRead(d, meta)
}

func resourceAgentRegistryMcpServerRead(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/services/{{mcp_server_id}}")
	if err != nil {
		return err
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for McpServer: %s", err)
	}
	billingProject = project

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "GET",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Headers:   headers,
	})
	if err != nil {
		return transport_tpg.HandleNotFoundError(err, d, fmt.Sprintf("AgentRegistryMcpServer %q", d.Id()))
	}

	log.Printf("[DEBUG] Finished reading AgentRegistryMcpServer %q: %#v", d.Id(), res)

	// Explicitly set virtual fields to default values if unset
	if _, ok := d.GetOkExists("deletion_policy"); !ok {
		//prioritize config's value if present
		if config.DeletionPolicy != "" {
			if err := d.Set("deletion_policy", config.DeletionPolicy); err != nil {
				return fmt.Errorf("Error setting deletion_policy: %s", err)
			}
		} else {
			if err := d.Set("deletion_policy", "DELETE"); err != nil {
				return fmt.Errorf("Error setting deletion_policy: %s", err)
			}
		}
	}
	if err := d.Set("project", project); err != nil {
		return fmt.Errorf("Error reading McpServer: %s", err)
	}

	err = ResourceAgentRegistryMcpServerFlatten(d, meta, res, config, project, userAgent, billingProject, url, headers)
	if err != nil {
		return err
	}

	identity, err := d.Identity()
	if err == nil && identity != nil {
		if v, ok := identity.GetOk("location"); !ok && v == "" {
			err = identity.Set("location", d.Get("location").(string))
			if err != nil {
				return fmt.Errorf("Error setting location: %s", err)
			}
		}
		if v, ok := identity.GetOk("mcp_server_id"); !ok && v == "" {
			err = identity.Set("mcp_server_id", d.Get("mcp_server_id").(string))
			if err != nil {
				return fmt.Errorf("Error setting mcp_server_id: %s", err)
			}
		}
		if v, ok := identity.GetOk("project"); !ok && v == "" {
			err = identity.Set("project", d.Get("project").(string))
			if err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Read) identity not set: %s", err)
	}

	return nil
}

func resourceAgentRegistryMcpServerUpdate(d *schema.ResourceData, meta interface{}) error {
	clientSideFields := map[string]bool{"deletion_policy": true}
	clientSideOnly := true
	for field := range ResourceAgentRegistryMcpServer().Schema {
		if d.HasChange(field) && !clientSideFields[field] {
			clientSideOnly = false
			break
		}
	}
	if clientSideOnly {
		log.Print("[DEBUG] Only client-side changes detected. Cancelling update operation.")
		return resourceAgentRegistryMcpServerRead(d, meta)
	}

	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}
	identity, err := d.Identity()
	if err == nil && identity != nil {
		if locationValue, ok := d.GetOk("location"); ok && locationValue.(string) != "" {
			if err = identity.Set("location", locationValue.(string)); err != nil {
				return fmt.Errorf("Error setting location: %s", err)
			}
		}
		if mcpServerIdValue, ok := d.GetOk("mcp_server_id"); ok && mcpServerIdValue.(string) != "" {
			if err = identity.Set("mcp_server_id", mcpServerIdValue.(string)); err != nil {
				return fmt.Errorf("Error setting mcp_server_id: %s", err)
			}
		}
		if projectValue, ok := d.GetOk("project"); ok && projectValue.(string) != "" {
			if err = identity.Set("project", projectValue.(string)); err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Update) identity not set: %s", err)
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for McpServer: %s", err)
	}
	billingProject = project

	obj := make(map[string]interface{})
	displayNameProp, err := expandAgentRegistryMcpServerDisplayName(d.Get("display_name"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("display_name"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, displayNameProp)) {
		obj["displayName"] = displayNameProp
	}
	descriptionProp, err := expandAgentRegistryMcpServerDescription(d.Get("description"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("description"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, descriptionProp)) {
		obj["description"] = descriptionProp
	}
	interfacesProp, err := expandAgentRegistryMcpServerInterfaces(d.Get("interfaces"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("interfaces"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, interfacesProp)) {
		obj["interfaces"] = interfacesProp
	}
	mcpServerSpecProp, err := expandAgentRegistryMcpServerMcpServerSpec(d.Get("mcp_server_spec"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("mcp_server_spec"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, mcpServerSpecProp)) {
		obj["mcpServerSpec"] = mcpServerSpecProp
	}

	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/services/{{mcp_server_id}}")
	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Updating McpServer %q: %#v", d.Id(), obj)
	headers := make(http.Header)
	updateMask := []string{}

	if d.HasChange("display_name") {
		updateMask = append(updateMask, "displayName")
	}

	if d.HasChange("description") {
		updateMask = append(updateMask, "description")
	}

	if d.HasChange("interfaces") {
		updateMask = append(updateMask, "interfaces")
	}

	if d.HasChange("mcp_server_spec") {
		updateMask = append(updateMask, "mcpServerSpec")
	}
	// updateMask is a URL parameter but not present in the schema, so ReplaceVars
	// won't set it
	url, err = transport_tpg.AddQueryParams(url, map[string]string{"updateMask": strings.Join(updateMask, ",")})
	if err != nil {
		return err
	}

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	// if updateMask is empty we are not updating anything so skip the post
	if len(updateMask) > 0 {
		res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
			Config:    config,
			Method:    "PATCH",
			Project:   billingProject,
			RawURL:    url,
			UserAgent: userAgent,
			Body:      obj,
			Timeout:   d.Timeout(schema.TimeoutUpdate),
			Headers:   headers,
		})

		if err != nil {
			return fmt.Errorf("Error updating McpServer %q: %s", d.Id(), err)
		} else {
			log.Printf("[DEBUG] Finished updating McpServer %q: %#v", d.Id(), res)
		}

		err = AgentRegistryOperationWaitTime(
			config, res, project, "Updating McpServer", userAgent,
			d.Timeout(schema.TimeoutUpdate))

		if err != nil {
			return err
		}
	}

	return resourceAgentRegistryMcpServerRead(d, meta)
}

func resourceAgentRegistryMcpServerDelete(d *schema.ResourceData, meta interface{}) error {
	if d.Get("deletion_policy").(string) == "PREVENT" {
		return fmt.Errorf("cannot destroy AgentRegistryMcpServer without setting deletion_policy=\"DELETE\" and running `terraform apply`")
	}
	if d.Get("deletion_policy").(string) == "ABANDON" {
		log.Printf("[DEBUG] deletion_policy set to \"ABANDON\", removing McpServer %q from Terraform state without deletion", d.Id())
		return nil
	}
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for McpServer: %s", err)
	}
	billingProject = project
	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/services/{{mcp_server_id}}")
	if err != nil {
		return err
	}

	var obj map[string]interface{}

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)

	log.Printf("[DEBUG] Deleting McpServer %q", d.Id())
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "DELETE",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
		Timeout:   d.Timeout(schema.TimeoutDelete),
		Headers:   headers,
	})
	if err != nil {
		return transport_tpg.HandleNotFoundError(err, d, "McpServer")
	}

	err = AgentRegistryOperationWaitTime(
		config, res, project, "Deleting McpServer", userAgent,
		d.Timeout(schema.TimeoutDelete))

	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Finished deleting McpServer %q: %#v", d.Id(), res)
	return nil
}

func resourceAgentRegistryMcpServerImport(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	config := meta.(*transport_tpg.Config)
	if err := tpgresource.ParseImportId([]string{
		"^projects/(?P<project>[^/]+)/locations/(?P<location>[^/]+)/services/(?P<mcp_server_id>[^/]+)$",
		"^(?P<project>[^/]+)/(?P<location>[^/]+)/(?P<mcp_server_id>[^/]+)$",
		"^(?P<location>[^/]+)/(?P<mcp_server_id>[^/]+)$",
	}, d, config); err != nil {
		return nil, err
	}

	// Replace import id for the resource id
	id, err := tpgresource.ReplaceVars(d, config, "projects/{{project}}/locations/{{location}}/services/{{mcp_server_id}}")
	if err != nil {
		return nil, fmt.Errorf("Error constructing id: %s", err)
	}
	d.SetId(id)

	return []*schema.ResourceData{d}, nil
}

func flattenAgentRegistryMcpServerName(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenAgentRegistryMcpServerDisplayName(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenAgentRegistryMcpServerDescription(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenAgentRegistryMcpServerRegistryResource(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenAgentRegistryMcpServerCreateTime(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenAgentRegistryMcpServerUpdateTime(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenAgentRegistryMcpServerInterfaces(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}
	l := v.([]interface{})
	transformed := make([]interface{}, 0, len(l))
	for _, raw := range l {
		original := raw.(map[string]interface{})
		if len(original) < 1 {
			// Do not include empty json objects coming back from the api
			continue
		}
		transformed = append(transformed, map[string]interface{}{
			"url":              flattenAgentRegistryMcpServerInterfacesUrl(original["url"], d, config),
			"protocol_binding": flattenAgentRegistryMcpServerInterfacesProtocolBinding(original["protocolBinding"], d, config),
		})
	}
	return transformed
}
func flattenAgentRegistryMcpServerInterfacesUrl(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenAgentRegistryMcpServerInterfacesProtocolBinding(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenAgentRegistryMcpServerMcpServerSpec(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	if len(original) == 0 {
		return nil
	}
	transformed := make(map[string]interface{})
	transformed["type"] =
		flattenAgentRegistryMcpServerMcpServerSpecType(original["type"], d, config)
	transformed["content"] =
		flattenAgentRegistryMcpServerMcpServerSpecContent(original["content"], d, config)
	return []interface{}{transformed}
}
func flattenAgentRegistryMcpServerMcpServerSpecType(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenAgentRegistryMcpServerMcpServerSpecContent(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	b, err := json.Marshal(v)
	if err != nil {
		// TODO: return error once https://github.com/GoogleCloudPlatform/magic-modules/issues/3257 is fixed.
		log.Printf("[ERROR] failed to marshal schema to JSON: %v", err)
	}
	return string(b)
}

func expandAgentRegistryMcpServerDisplayName(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandAgentRegistryMcpServerDescription(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandAgentRegistryMcpServerInterfaces(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	if v == nil {
		return nil, nil
	}
	l := v.([]interface{})
	req := make([]interface{}, 0, len(l))
	for _, raw := range l {
		if raw == nil {
			continue
		}
		original := raw.(map[string]interface{})
		transformed := make(map[string]interface{})

		transformedUrl, err := expandAgentRegistryMcpServerInterfacesUrl(original["url"], d, config)
		if err != nil {
			return nil, err
		} else if val := reflect.ValueOf(transformedUrl); val.IsValid() && !tpgresource.IsEmptyValue(val) {
			transformed["url"] = transformedUrl
		}

		transformedProtocolBinding, err := expandAgentRegistryMcpServerInterfacesProtocolBinding(original["protocol_binding"], d, config)
		if err != nil {
			return nil, err
		} else if val := reflect.ValueOf(transformedProtocolBinding); val.IsValid() && !tpgresource.IsEmptyValue(val) {
			transformed["protocolBinding"] = transformedProtocolBinding
		}

		req = append(req, transformed)
	}
	return req, nil
}

func expandAgentRegistryMcpServerInterfacesUrl(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandAgentRegistryMcpServerInterfacesProtocolBinding(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandAgentRegistryMcpServerMcpServerSpec(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	if v == nil {
		return nil, nil
	}
	l := v.([]interface{})
	if len(l) == 0 || l[0] == nil {
		return nil, nil
	}
	raw := l[0]
	original := raw.(map[string]interface{})
	transformed := make(map[string]interface{})

	transformedType, err := expandAgentRegistryMcpServerMcpServerSpecType(original["type"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedType); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["type"] = transformedType
	}

	transformedContent, err := expandAgentRegistryMcpServerMcpServerSpecContent(original["content"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedContent); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["content"] = transformedContent
	}

	return transformed, nil
}

func expandAgentRegistryMcpServerMcpServerSpecType(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandAgentRegistryMcpServerMcpServerSpecContent(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	b := []byte(v.(string))
	if len(b) == 0 {
		return nil, nil
	}
	m := make(map[string]interface{})
	if err := json.Unmarshal(b, &m); err != nil {
		return nil, err
	}
	return m, nil
}

func ResourceAgentRegistryMcpServerFlatten(d *schema.ResourceData, meta interface{}, res map[string]interface{}, config *transport_tpg.Config, project string, userAgent string, billingProject string, url string, headers http.Header) error {
	var err error

	if err = d.Set("name", flattenAgentRegistryMcpServerName(res["name"], d, config)); err != nil {
		return fmt.Errorf("Error reading McpServer: %s", err)
	}
	if err = d.Set("display_name", flattenAgentRegistryMcpServerDisplayName(res["displayName"], d, config)); err != nil {
		return fmt.Errorf("Error reading McpServer: %s", err)
	}
	if err = d.Set("description", flattenAgentRegistryMcpServerDescription(res["description"], d, config)); err != nil {
		return fmt.Errorf("Error reading McpServer: %s", err)
	}
	if err = d.Set("registry_resource", flattenAgentRegistryMcpServerRegistryResource(res["registryResource"], d, config)); err != nil {
		return fmt.Errorf("Error reading McpServer: %s", err)
	}
	if err = d.Set("create_time", flattenAgentRegistryMcpServerCreateTime(res["createTime"], d, config)); err != nil {
		return fmt.Errorf("Error reading McpServer: %s", err)
	}
	if err = d.Set("update_time", flattenAgentRegistryMcpServerUpdateTime(res["updateTime"], d, config)); err != nil {
		return fmt.Errorf("Error reading McpServer: %s", err)
	}
	if err = d.Set("interfaces", flattenAgentRegistryMcpServerInterfaces(res["interfaces"], d, config)); err != nil {
		return fmt.Errorf("Error reading McpServer: %s", err)
	}
	if err = d.Set("mcp_server_spec", flattenAgentRegistryMcpServerMcpServerSpec(res["mcpServerSpec"], d, config)); err != nil {
		return fmt.Errorf("Error reading McpServer: %s", err)
	}

	return nil
}
