# Copyright IBM Corp. 2014, 2026
# SPDX-License-Identifier: MPL-2.0
resource: google_apigee_api_deployment
generation_type: mmv1
source_file: products/apigee/ApiDeployment.yaml
api_service_name: apigee.googleapis.com
api_version: v1
api_resource_type_kind: ApiDeployment
fields:
    - api_field: environment
    - api_field: id
    - api_field: org_id
    - api_field: proxy_id
    - api_field: revision
    - field: deletion_policy
      provider_only: true
