resource: 'google_apihub_attribute_allowed_values'
generation_type: 'mmv1'
source_file: 'products/apihub/AttributeAllowedValues.yaml'
api_service_name: 'apihub.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'AttributeAllowedValues'
fields:
  - field: 'allowed_values.description'
  - field: 'allowed_values.display_name'
  - field: 'allowed_values.id'
  - field: 'allowed_values.immutable'
  - field: 'attribute_id'
    provider_only: true
  - field: 'location'
    provider_only: true
