// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/networksecurity/GatewaySecurityPolicyRule.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/list_resource.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package networksecurity

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/list"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"

	"github.com/hashicorp/terraform-provider-google-beta/google-beta/registry"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
)

func init() {
	registry.FrameworkListResource{
		Name:        "google_network_security_gateway_security_policy_rule",
		ProductName: "NetworkSecurity",
		Func:        NewNetworkSecurityGatewaySecurityPolicyRuleListResource,
	}.Register()
}

var _ list.ListResource = &NetworkSecurityGatewaySecurityPolicyRuleListResource{}

type NetworkSecurityGatewaySecurityPolicyRuleListResource struct {
	tpgresource.ListResourceMetadata
}

func NewNetworkSecurityGatewaySecurityPolicyRuleListResource() list.ListResource {
	listR := &NetworkSecurityGatewaySecurityPolicyRuleListResource{}
	listR.TypeName = "google_network_security_gateway_security_policy_rule"
	listR.SDKv2Resource = ResourceNetworkSecurityGatewaySecurityPolicyRule()
	listR.ListConfigFields = []tpgresource.ListConfigField{
		{Name: "location", Kind: tpgresource.ListConfigKindString, Optional: false},
		{Name: "gateway_security_policy", Kind: tpgresource.ListConfigKindString, Optional: false},
		{Name: "project", Kind: tpgresource.ListConfigKindString, Optional: true},
	}
	return listR
}

// NetworkSecurityGatewaySecurityPolicyRuleListModel matches ListResourceMetadata.ListConfigFields (tfsdk names and types).
type NetworkSecurityGatewaySecurityPolicyRuleListModel struct {
	Location              types.String `tfsdk:"location"`
	GatewaySecurityPolicy types.String `tfsdk:"gateway_security_policy"`
	Project               types.String `tfsdk:"project"`
}

func (listR *NetworkSecurityGatewaySecurityPolicyRuleListResource) List(ctx context.Context, listReq list.ListRequest, stream *list.ListResultsStream) {
	var data NetworkSecurityGatewaySecurityPolicyRuleListModel
	diags := listReq.Config.Get(ctx, &data)
	if diags.HasError() {
		stream.Results = list.ListResultsStreamDiagnostics(diags)
		return
	}
	if listR.Client == nil {
		diags = append(diags, diag.NewErrorDiagnostic(
			"Provider not configured",
			"The Google provider client is not available; ensure the provider is configured (e.g. credentials and default project).",
		))
		stream.Results = list.ListResultsStreamDiagnostics(diags)
		return
	}
	location := listR.GetLocation(data.Location)
	gatewaySecurityPolicy := data.GatewaySecurityPolicy.ValueString()
	project := listR.GetProject(data.Project)

	errStreamClosed := errors.New("stream closed")
	stream.Results = func(push func(list.ListResult) bool) {
		err := ListNetworkSecurityGatewaySecurityPolicyRules(
			listR.Client,
			location,
			gatewaySecurityPolicy,
			project,
			func(rd *schema.ResourceData) error {
				result := listReq.NewListResult(ctx)

				if err := listR.SetResult(ctx, listReq.IncludeResource, &result, rd, "name"); err != nil {
					return err
				}

				if !push(result) {
					return errStreamClosed
				}
				return nil
			},
		)
		// A closed stream is not an error: return without pushing again.
		if err == nil || errors.Is(err, errStreamClosed) {
			return
		}
		diags.AddError("API Error", err.Error())
		result := listReq.NewListResult(ctx)
		result.Diagnostics = diags
		push(result)
	}
}

func ListNetworkSecurityGatewaySecurityPolicyRules(config *transport_tpg.Config,
	location string,
	gatewaySecurityPolicy string,
	project string,
	callback func(*schema.ResourceData) error,
) error {
	resourceData := ResourceNetworkSecurityGatewaySecurityPolicyRule().Data(&terraform.InstanceState{})
	if location != "" {
		if err := resourceData.Set("location", location); err != nil {
			return fmt.Errorf("error setting location on temporary resource data: %w", err)
		}
	}
	if gatewaySecurityPolicy != "" {
		if err := resourceData.Set("gateway_security_policy", gatewaySecurityPolicy); err != nil {
			return fmt.Errorf("error setting gateway_security_policy on temporary resource data: %w", err)
		}
	}
	if project != "" {
		if err := resourceData.Set("project", project); err != nil {
			return fmt.Errorf("error setting project on temporary resource data: %w", err)
		}
	}

	url, err := tpgresource.ReplaceVars(resourceData, config, "{{NetworkSecurityBasePath}}projects/{{project}}/locations/{{location}}/gatewaySecurityPolicies/{{gateway_security_policy}}/rules")
	if err != nil {
		return err
	}
	billingProject := project
	if bp, err := tpgresource.GetBillingProject(resourceData, config); err == nil {
		billingProject = bp
	}

	userAgent, err := tpgresource.GenerateUserAgentString(resourceData, config.UserAgent)
	if err != nil {
		return err
	}

	return transport_tpg.ListPages(transport_tpg.ListPagesOptions{
		Config:         config,
		TempData:       resourceData,
		Resource:       ResourceNetworkSecurityGatewaySecurityPolicyRule(),
		ListURL:        url,
		BillingProject: billingProject,
		UserAgent:      userAgent,
		ItemName:       "gatewaySecurityPolicyRules",
		Flattener: func(res map[string]interface{}, d *schema.ResourceData, config *transport_tpg.Config) error {
			headers := make(http.Header)
			var err error
			if v, ok := res["name"]; ok && v != nil {
				if err := d.Set("name", v); err != nil {
					return fmt.Errorf("error setting name: %w", err)
				}
			}
			if v, ok := res["location"]; ok && v != nil {
				if err := d.Set("location", v); err != nil {
					return fmt.Errorf("error setting location: %w", err)
				}
			}
			if v, ok := res["gateway_security_policy"]; ok && v != nil {
				if err := d.Set("gateway_security_policy", v); err != nil {
					return fmt.Errorf("error setting gateway_security_policy: %w", err)
				}
			}
			if err = ResourceNetworkSecurityGatewaySecurityPolicyRuleFlatten(d, config, res, config, project, userAgent, billingProject, url, headers); err != nil {
				return err
			}
			id, err := tpgresource.ReplaceVars(d, config, "projects/{{project}}/locations/{{location}}/gatewaySecurityPolicies/{{gateway_security_policy}}/rules/{{name}}")
			if err != nil {
				return fmt.Errorf("error constructing id: %w", err)
			}
			d.SetId(id)
			return nil
		},
		Callback: callback,
	})
}
