// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/networksecurity/TlsInspectionPolicy.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/samples/base_configs/query_test_file.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package networksecurity_test

import (
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/querycheck"
	"github.com/hashicorp/terraform-plugin-testing/querycheck/queryfilter"
	"github.com/hashicorp/terraform-plugin-testing/tfversion"

	"github.com/hashicorp/terraform-provider-google-beta/google-beta/acctest"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/envvar"
	_ "github.com/hashicorp/terraform-provider-google-beta/google-beta/services/networksecurity"
	_ "github.com/hashicorp/terraform-provider-google-beta/google-beta/services/privateca"
	_ "github.com/hashicorp/terraform-provider-google-beta/google-beta/services/resourcemanager"
)

var (
	_ = strings.Trim
	_ = envvar.TestEnvVar
)

func TestAccNetworkSecurityTlsInspectionPolicyListQuery_generated(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)
	context := map[string]interface{}{
		"privateca_ca_pool_name":             "tf-test-my-basic-ca-pool" + randomSuffix,
		"privateca_certificate_authority_id": "tf-test-my-basic-certificate-authority" + randomSuffix,
		"resource_name":                      "tf-test-my-tls-inspection-policy" + randomSuffix,
		"project":                            envvar.GetTestProjectFromEnv(),
		"random_suffix":                      randomSuffix,
	}

	var listDisplayName acctest.ListDisplayName
	var listScope acctest.ListScopeCapture
	acctest.VcrTest(t, resource.TestCase{
		TerraformVersionChecks: []tfversion.TerraformVersionCheck{
			tfversion.SkipBelow(tfversion.Version1_14_0),
		},
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		CheckDestroy:             testAccCheckNetworkSecurityTlsInspectionPolicyDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccNetworkSecurityTlsInspectionPolicy_networkSecurityTlsInspectionPolicyBasicExample(context),
				Check: resource.ComposeTestCheckFunc(
					listDisplayName.Capture(
						"google_network_security_tls_inspection_policy.default",
						[]string{
							"name",
						},
					),
					listScope.Capture(map[string]string{}),
				),
			},
			{
				Query:           true,
				Config:          testAccNetworkSecurityTlsInspectionPolicy_networkSecurityTlsInspectionPolicyBasicExampleListQuery(context),
				ConfigVariables: listScope.AsConfigVariables(),
				QueryResultChecks: []querycheck.QueryResultCheck{
					querycheck.ExpectLengthAtLeast("google_network_security_tls_inspection_policy.list_query", 1),
					querycheck.ExpectResourceDisplayName(
						"google_network_security_tls_inspection_policy.list_query",
						queryfilter.ByDisplayName(listDisplayName.CheckValue()),
						listDisplayName.CheckValue(),
					),
				},
			},
		},
	})
}

func testAccNetworkSecurityTlsInspectionPolicy_networkSecurityTlsInspectionPolicyBasicExampleListQuery(context map[string]interface{}) string {
	return acctest.Nprintf(`
list "google_network_security_tls_inspection_policy" "list_query" {
    provider = google
	limit = 10000
    config {
    }
}
`, context)
}
