// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package bigqueryanalyticshub_test

import (
	"fmt"
	"log"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-beta/google-beta/acctest"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/envvar"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"

	"google.golang.org/api/googleapi"
)

var (
	_ = fmt.Sprintf
	_ = log.Print
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = resource.TestMain
	_ = terraform.NewState
	_ = envvar.TestEnvVar
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = googleapi.Error{}
)

func TestAccBigqueryAnalyticsHubQueryTemplate_bigqueryAnalyticshubQueryTemplateBasicExample(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix": acctest.RandString(t, 10),
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckBigqueryAnalyticsHubQueryTemplateDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccBigqueryAnalyticsHubQueryTemplate_bigqueryAnalyticshubQueryTemplateBasicExample(context),
			},
			{
				ResourceName:            "google_bigquery_analytics_hub_query_template.querytemplate",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"data_exchange_id", "location", "query_template_id", "submit"},
			},
		},
	})
}

func testAccBigqueryAnalyticsHubQueryTemplate_bigqueryAnalyticshubQueryTemplateBasicExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_bigquery_analytics_hub_data_exchange" "querytemplate" {
  display_name = "My Audience Data Exchange"
  data_exchange_id = "tf_test_my_data_exchange%{random_suffix}"
  description = "example of query template%{random_suffix}"
  location = "us"
  sharing_environment_config {
    dcr_exchange_config {}
  }
}

resource "google_bigquery_analytics_hub_query_template" "querytemplate" {
  location = "us"
  data_exchange_id = google_bigquery_analytics_hub_data_exchange.querytemplate.data_exchange_id
  query_template_id = "qt1%{random_suffix}"
  display_name = "qt1%{random_suffix}"
  description = "example of query template%{random_suffix}"
  primary_contact = "admin@example.com"
  documentation = "This TVF takes a table t1 as input and returns all columns. Useful for basic data pass-through."
  routine {
    routine_type="TABLE_VALUED_FUNCTION"
    definition_body="qt1%{random_suffix}(t1 ANY TABLE) as (select * from t1)"
  }
  submit=false
  provider = google-beta
}
`, context)
}

func testAccCheckBigqueryAnalyticsHubQueryTemplateDestroyProducer(t *testing.T) func(s *terraform.State) error {
	return func(s *terraform.State) error {
		for name, rs := range s.RootModule().Resources {
			if rs.Type != "google_bigquery_analytics_hub_query_template" {
				continue
			}
			if strings.HasPrefix(name, "data.") {
				continue
			}

			config := acctest.GoogleProviderConfig(t)

			url, err := tpgresource.ReplaceVarsForTest(config, rs, "{{BigqueryAnalyticsHubBasePath}}projects/{{project}}/locations/{{location}}/dataExchanges/{{data_exchange_id}}/queryTemplates/{{query_template_id}}")
			if err != nil {
				return err
			}

			billingProject := ""

			if config.BillingProject != "" {
				billingProject = config.BillingProject
			}

			_, err = transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
				Config:    config,
				Method:    "GET",
				Project:   billingProject,
				RawURL:    url,
				UserAgent: config.UserAgent,
			})
			if err == nil {
				return fmt.Errorf("BigqueryAnalyticsHubQueryTemplate still exists at %s", url)
			}
		}

		return nil
	}
}
