// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package dataplex_test

import (
	"fmt"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-beta/google-beta/acctest"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/envvar"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
)

func TestAccDataplexCategory_dataplexCategoryBasicExample(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"project_name":  envvar.GetTestProjectFromEnv(),
		"random_suffix": acctest.RandString(t, 10),
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		CheckDestroy:             testAccCheckDataplexCategoryDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccDataplexCategory_dataplexCategoryBasicExample(context),
			},
			{
				ResourceName:            "google_dataplex_category.category_test_id",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"category_id", "glossary_id", "labels", "location", "terraform_labels"},
			},
		},
	})
}

func testAccDataplexCategory_dataplexCategoryBasicExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_dataplex_glossary" "category_test_id" {
  name        = "tf-test-glossary%{random_suffix}"
  location    = "<no value>"
  project     = "%{project_name}"
}

resource "google_dataplex_category" "category_test_id" {
  parent         = "projects/%{project_name}/locations/<no value>/glossaries/${google_dataplex_glossary.glossary.name}"
  glossary_id     = google_dataplex_glossary.category_test_id.name
  location    = "<no value>"
  project     = "%{project_name}"
  category_id = "tf-test-category%{random_suffix}"
}
`, context)
}

func TestAccDataplexCategory_dataplexCategoryFullExample(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"project_name":  envvar.GetTestProjectFromEnv(),
		"random_suffix": acctest.RandString(t, 10),
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		CheckDestroy:             testAccCheckDataplexCategoryDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccDataplexCategory_dataplexCategoryFullExample(context),
			},
			{
				ResourceName:            "google_dataplex_category.category_test_id_full",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"category_id", "glossary_id", "labels", "location", "terraform_labels"},
			},
		},
	})
}

func testAccDataplexCategory_dataplexCategoryFullExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_dataplex_glossary" "category_test_id_full" {
  name        = "tf-test-glossary%{random_suffix}"
  location    = "<no value>"
  project     = "%{project_name}"
}

resource "google_dataplex_category" "category_test_id_full" {
  parent         = "projects/%{project_name}/locations/<no value>/glossaries/${google_dataplex_glossary.glossary.name}"
  glossary_id     = google_dataplex_glossary.category_test_id_full.name
  location    = "<no value>"
  project     = "%{project_name}"
  category_id = "tf-test-category%{random_suffix}"

  labels = { "tag": "test-tf" }
  display_name = "terraform category"
  description = "category created by Terraform"
}
`, context)
}

func testAccCheckDataplexCategoryDestroyProducer(t *testing.T) func(s *terraform.State) error {
	return func(s *terraform.State) error {
		for name, rs := range s.RootModule().Resources {
			if rs.Type != "google_dataplex_category" {
				continue
			}
			if strings.HasPrefix(name, "data.") {
				continue
			}

			config := acctest.GoogleProviderConfig(t)

			url, err := tpgresource.ReplaceVarsForTest(config, rs, "{{DataplexBasePath}}projects/{{project}}/locations/{{location}}/glossaries/{{glossary_id}}/categories/{{category_id}}")
			if err != nil {
				return err
			}

			billingProject := ""

			if config.BillingProject != "" {
				billingProject = config.BillingProject
			}

			_, err = transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
				Config:    config,
				Method:    "GET",
				Project:   billingProject,
				RawURL:    url,
				UserAgent: config.UserAgent,
			})
			if err == nil {
				return fmt.Errorf("DataplexCategory still exists at %s", url)
			}
		}

		return nil
	}
}
