resource: 'google_storage_bucket_life_cycle_config'
generation_type: 'mmv1'
source_file: 'products/storage/LifeCycle.yaml'
api_service_name: 'storage.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'BucketLifeCycleConfig'
fields:
  - field: 'bucket'
    provider_only: true
  - field: 'create_time'
  - field: 'lifecycle_rule.action.storage_class'
  - field: 'lifecycle_rule.action.type'
  - field: 'lifecycle_rule.condition.age'
  - field: 'lifecycle_rule.condition.created_before'
  - field: 'lifecycle_rule.condition.custom_time_before'
  - field: 'lifecycle_rule.condition.days_since_custom_time'
  - field: 'lifecycle_rule.condition.days_since_noncurrent_time'
  - field: 'lifecycle_rule.condition.matches_prefix'
  - field: 'lifecycle_rule.condition.matches_storage_class'
  - field: 'lifecycle_rule.condition.matches_suffix'
  - field: 'lifecycle_rule.condition.noncurrent_time_before'
  - field: 'lifecycle_rule.condition.num_newer_versions'
  - field: 'lifecycle_rule.condition.send_age_if_zero'
  - field: 'lifecycle_rule.condition.send_days_since_custom_time_if_zero'
  - field: 'lifecycle_rule.condition.send_days_since_noncurrent_time_if_zero'
  - field: 'lifecycle_rule.condition.send_num_newer_versions_if_zero'
  - field: 'lifecycle_rule.condition.with_state'
  - field: 'update_time'
