// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package modelarmorglobal_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/hashicorp/terraform-provider-google-beta/google-beta/acctest"
)

func TestAccModelArmorGlobalFloorsetting_modelarmorFloorsettingBasicExample(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"location":      "global",
		"parent":        "projects/modelarmor-api-test",
		"random_suffix": acctest.RandString(t, 10),
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccModelArmorGlobalFloorsetting_modelarmorFloorsettingBasicExample(context),
			},
			{
				ResourceName:            "google_model_armor_floorsetting.floorsetting-basic",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"location", "parent"},
			},
		},
	})
}

func testAccModelArmorGlobalFloorsetting_modelarmorFloorsettingBasicExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_model_armor_floorsetting" "floorsetting-basic" {
  parent      = "%{parent}"
  location    = "%{location}"

  filter_config {

  }
}
`, context)
}

func TestAccModelArmorGlobalFloorsetting_modelarmorFloorsettingFilterConfigExample(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"enable_floor_setting_enforcement":                                  true,
		"filter_config_malicious_uri_filter_settings_filter_enforcement":    "ENABLED",
		"filter_config_pi_and_jailbreak_filter_settings_confidence_level":   "HIGH",
		"filter_config_pi_and_jailbreak_filter_settings_filter_enforcement": "ENABLED",
		"filter_config_rai_settings_rai_filters_0_confidence_level":         "MEDIUM_AND_ABOVE",
		"filter_config_rai_settings_rai_filters_0_filter_type":              "DANGEROUS",
		"filter_config_sdp_settings_basic_config_filter_enforcement":        "ENABLED",
		"location":                 "global",
		"parent":                   "organizations/31999524790",
		"sdp_settings_config_type": "basic_config",
		"random_suffix":            acctest.RandString(t, 10),
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccModelArmorGlobalFloorsetting_modelarmorFloorsettingFilterConfigExample(context),
			},
			{
				ResourceName:            "google_model_armor_floorsetting.floorsetting-filter-config",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"location", "parent"},
			},
		},
	})
}

func testAccModelArmorGlobalFloorsetting_modelarmorFloorsettingFilterConfigExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_model_armor_floorsetting" "floorsetting-filter-config" {
  location    = "%{location}"
  parent      = "%{parent}"

  filter_config {
    rai_settings {
      rai_filters {
        filter_type      = "%{filter_config_rai_settings_rai_filters_0_filter_type}"
        confidence_level = "%{filter_config_rai_settings_rai_filters_0_confidence_level}"
      }
    }
    sdp_settings {
      basic_config {
          filter_enforcement = "%{filter_config_sdp_settings_basic_config_filter_enforcement}"
      }
    }
    pi_and_jailbreak_filter_settings {
      filter_enforcement = "%{filter_config_pi_and_jailbreak_filter_settings_filter_enforcement}"
      confidence_level   = "%{filter_config_pi_and_jailbreak_filter_settings_confidence_level}"
    }
    malicious_uri_filter_settings {
      filter_enforcement = "%{filter_config_malicious_uri_filter_settings_filter_enforcement}"
    }
  }

  enable_floor_setting_enforcement = %{enable_floor_setting_enforcement}
}
`, context)
}

func TestAccModelArmorGlobalFloorsetting_modelarmorFloorsettingAiPlatformMetadataExample(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"ai_platform_floor_setting_enable_cloud_logging":          true,
		"ai_platform_floor_setting_enforcement_type_inspect_only": true,
		"enable_floor_setting_enforcement":                        false,
		"floor_setting_metadata_multi_language_detection":         false,
		"location":      "global",
		"parent":        "folders/710206369120",
		"random_suffix": acctest.RandString(t, 10),
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccModelArmorGlobalFloorsetting_modelarmorFloorsettingAiPlatformMetadataExample(context),
			},
			{
				ResourceName:            "google_model_armor_floorsetting.floorsetting-integrated-metadata",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"location", "parent"},
			},
		},
	})
}

func testAccModelArmorGlobalFloorsetting_modelarmorFloorsettingAiPlatformMetadataExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_model_armor_floorsetting" "floorsetting-integrated-metadata" {
  location    = "%{location}"
  parent      = "%{parent}"

  filter_config {
  
  }

  enable_floor_setting_enforcement = "%{enable_floor_setting_enforcement}"
  
  ai_platform_floor_setting {
    inspect_only            = %{ai_platform_floor_setting_enforcement_type_inspect_only}
    enable_cloud_logging    = %{ai_platform_floor_setting_enable_cloud_logging}
  }
  
  floor_setting_metadata {
    multi_language_detection {
      enable_multi_language_detection = %{floor_setting_metadata_multi_language_detection}
    }
  }
}
`, context)
}
